INSERT INTO public.challenges (slug,title,type,specialty,xp_reward,description,tags) VALUES
  ('p0171-lean-bank1','P0171 — System Too Lean (Bank 1)','dtc','Automotive',100,'2020 Toyota Camry 2.5L. MIL on, slight hesitation at light throttle.',ARRAY['Fuel Trim','MAF','Vacuum Leak']),
  ('lh-low-beam-open','Open Circuit — LH Low Beam','wiring','Automotive',90,'2021 Ford F-250. Left low beam inop. Fuse OK, new bulb — still no light.',ARRAY['Lighting','Open Circuit','Voltage Drop']),
  ('p0401-egr-flow','P0401 — Insufficient EGR Flow','dtc','Diesel',130,'2019 Peterbilt 389 Paccar MX-13. P0401. Mild power loss on grades.',ARRAY['EGR','Emissions','Class 8']),
  ('6-7-balance-rates','Injector Balance Rates — 6.7 Powerstroke','component','Diesel',160,'2018 Ford F-350 6.7L. Rough idle, white smoke cold start.',ARRAY['Injectors','Fuel System','Ford 6.7']),
  ('voltage-drop-no-crank','Voltage Drop — Starter No-Crank','wiring','Automotive',110,'2019 Chevy Silverado 5.3L. Slow crank, sometimes no-crank.',ARRAY['Starting System','Voltage Drop','GM']),
  ('p0300-misfire-accord','P0300 — Random Misfire (Accord)','dtc','Automotive',120,'2017 Honda Accord 2.4L. P0300 + P0302.',ARRAY['Ignition','Misfire','Honda']),
  ('alternator-charging','Alternator Output & Charging Diagnosis','component','Automotive',100,'2016 Honda Civic 1.5T. Battery warning light intermittent.',ARRAY['Charging System','Alternator','Electrical']),
  ('can-bus-u-codes-ram','CAN Bus Fault — Multiple U-Codes','wiring','Diesel',150,'2020 Ram 2500 6.7 Cummins. Multiple U-codes after jump-start.',ARRAY['CAN Bus','Network Fault','Cummins'])
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'P0171 means Bank 1 is running lean. What does lean mean?','["Too much fuel, not enough air","Too much air, not enough fuel","Ignition timing is retarded","Coolant temp is low"]'::jsonb,1,'Lean = too much air relative to fuel. The ECM adds positive fuel trim trying to compensate.' FROM public.challenges WHERE slug='p0171-lean-bank1' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',1,'STFT +22%, LTFT +18% at idle — both drop near 0% at 2500 RPM. Most likely cause?','["Faulty MAF sensor reading low","Clogged fuel injectors","Vacuum leak downstream of the MAF","Weak fuel pump"]'::jsonb,2,'Trims high at idle normalizing at higher RPM is the classic vacuum leak pattern.' FROM public.challenges WHERE slug='p0171-lean-bank1' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',2,'Smoke test negative. MAF voltage 0.8V (spec 1.1-1.4V). LTFT +19%. Root cause and fix?','["Replace O2 sensor","Clean or replace MAF — underreporting airflow causing lean condition","Replace fuel pressure regulator","Reprogram ECM"]'::jsonb,1,'Dirty MAF underreports airflow so ECM injects less fuel.' FROM public.challenges WHERE slug='p0171-lean-bank1' ON CONFLICT DO NOTHING;

INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'Good fuse, new bulb, no light. Correct first electrical test?','["Replace headlamp switch","Check for battery voltage at bulb connector with circuit energized","Measure bulb filament resistance","Check battery negative terminal"]'::jsonb,1,'Follow the circuit with a voltmeter before replacing parts.' FROM public.challenges WHERE slug='lh-low-beam-open' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',1,'0V at bulb connector (circuit on). BCM output pin backprobed: 12.4V. Where is the open?','["Inside BCM output driver","In wire or connector between BCM and bulb","At headlamp switch input","Ground side of circuit"]'::jsonb,1,'Power leaves BCM but does not reach bulb — open is between those two points.' FROM public.challenges WHERE slug='lh-low-beam-open' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',2,'Pinched wire found — 0.4V drop under load (spec <0.1V). After repair what must you verify?','["Re-check fuse continuity only","Verify voltage drop <0.1V under load and confirm full light cycle","Road test 10 miles","Replace BCM as precaution"]'::jsonb,1,'Voltage drop test under load confirms repair quality.' FROM public.challenges WHERE slug='lh-low-beam-open' ON CONFLICT DO NOTHING;

INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'P0401 — insufficient EGR flow. First diagnostic step?','["Replace EGR valve","Verify EGR differential pressure sensor readings at idle with live data","Delete the emissions system","Check turbo boost pressure"]'::jsonb,1,'Confirm the fault with data before replacing parts.' FROM public.challenges WHERE slug='p0401-egr-flow' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',1,'EGR commanded 18%, actual delta pressure 0.2 inH2O (spec 1.8-3.2). Valve moves freely. What does this indicate?','["EGR valve solenoid shorted","Differential pressure sensor out of cal","EGR cooler or passages restricted","Turbo VGT vanes stuck open"]'::jsonb,2,'Valve works but measured flow near zero = physical restriction downstream.' FROM public.challenges WHERE slug='p0401-egr-flow' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',2,'After cleaning, flow delta 1.9 inH2O. Drive cycle complete — P0401 returns. Next step?','["Replace ECM","Inspect EGR cooler for internal bypass","Replace differential pressure sensor","Increase idle speed and retest"]'::jsonb,1,'Borderline flow + returning code = suspect internal EGR cooler damage.' FROM public.challenges WHERE slug='p0401-egr-flow' ON CONFLICT DO NOTHING;

INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'A large POSITIVE injector balance rate on a cylinder means:','["ECM adding fuel — injector delivering less than commanded","ECM reducing fuel — injector delivering more than commanded","Injector return circuit restricted","Injection timing advanced"]'::jsonb,1,'Positive = ECM trimming fuel DOWN — cylinder already over-contributing.' FROM public.challenges WHERE slug='6-7-balance-rates' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',1,'Balance rates: Cyl 1-2: -2.1, Cyl 3: +4.6, Cyl 4-6: -1.8, Cyl 7: +4.9, Cyl 8: -1.9. Correct interpretation?','["All 8 injectors need replacement","Cyl 3 and 7 are over-fueling; negatives are ECM compensating","Low rail pressure affecting all cylinders","Cyl 1,2,4,5,6,8 are misfiring"]'::jsonb,1,'Cyl 3 and 7 over-fueling. Other cylinders show ECM pulling fuel globally.' FROM public.challenges WHERE slug='6-7-balance-rates' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',2,'Cyl 3 and 7 replaced. Post-repair rates all -1.1 to -1.4. Rail pressure 4200 PSI (spec 4500-5500). Next?','["Replace all remaining injectors","Inspect HPFP and check injector return/leak-off","Recalibrate ECM injector trims","Check EGR operation"]'::jsonb,1,'Uniform negative rates + low rail pressure = HPFP worn or leak-off issue.' FROM public.challenges WHERE slug='6-7-balance-rates' ON CONFLICT DO NOTHING;

INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'Good battery, slow crank. Correct test to find resistance in starting circuit?','["Measure battery voltage key-off","Voltage drop test across each section while cranking","Replace starter motor","Check alternator output"]'::jsonb,1,'Voltage drop testing under load finds resistance open-circuit tests miss.' FROM public.challenges WHERE slug='voltage-drop-no-crank' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',1,'Cranking drop: Battery+ to starter B+: 0.8V, Battery- to starter case: 0.05V. Spec <0.2V each. Diagnosis?','["Starter motor faulty","Excessive resistance on positive feed side","Battery negative cable is the problem","BCM limiting starter current"]'::jsonb,1,'0.8V on positive far exceeds spec. Trace battery terminal to starter solenoid B+.' FROM public.challenges WHERE slug='voltage-drop-no-crank' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',2,'Cable ends repaired, drop now 0.18V/0.04V, cranks fast. Returns 3 days later — same slow crank. What was missed?','["Replace battery regardless","Check fusible link and chassis ground straps","Replace starter solenoid","Check alternator diode ripple"]'::jsonb,1,'Recurring symptoms after confirmed repair = second fault, often a ground strap.' FROM public.challenges WHERE slug='voltage-drop-no-crank' ON CONFLICT DO NOTHING;

INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'P0300 + P0302 stored. Quickest first test to isolate ignition vs fuel vs mechanical?','["Pull fuel injector and inspect","Swap cylinder 2 coil to a known-good cylinder","Replace all spark plugs","Check compression on all cylinders first"]'::jsonb,1,'Swap testing is fast and free. If P0302 moves = coil faulty.' FROM public.challenges WHERE slug='p0300-misfire-accord' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',1,'Coil swapped — P0302 stays on cyl 2. Compression cyl 2: 148 PSI, others 155-162. Injector PW matches. Next test?','["Declare low compression and recommend rebuild","Perform relative compression and injector drop test","Replace cyl 2 plug with different heat range","Check valve clearance on all cylinders"]'::jsonb,1,'Mild compression diff. A partially clogged injector can produce a misfire with normal compression.' FROM public.challenges WHERE slug='p0300-misfire-accord' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',2,'Injector drop passes. Running compression cyl 2: cranking 148 PSI, idle running 40 PSI (spec 70-80). What does this indicate?','["Head gasket failure to coolant jacket","Intake valve not fully closing — worn seat or burned valve","Exhaust manifold crack on cyl 2","PCV failure affecting crankcase pressure"]'::jsonb,1,'Normal cranking = rings fine. Low running compression = valve not seating under vacuum.' FROM public.challenges WHERE slug='p0300-misfire-accord' ON CONFLICT DO NOTHING;

INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'Battery light on at idle with accessories on. First check?','["Replace alternator immediately","Measure charging voltage — engine running, then with accessories on","Replace battery","Check serpentine belt tensioner"]'::jsonb,1,'Charging voltage test is the starting point.' FROM public.challenges WHERE slug='alternator-charging' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',1,'14.2V idle no-load. With AC/lights/blower max: drops to 12.6V idle, recovers to 13.8V at 2000 RPM. What does this indicate?','["Bad battery cell","Alternator output marginal at low RPM under high load","Voltage regulator set too low","Loose serpentine belt slipping"]'::jsonb,1,'Voltage below resting under load = alternator drawing from battery, not supplying it.' FROM public.challenges WHERE slug='alternator-charging' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',2,'Load test: max 68A (rated 150A). B+ to battery+: 0.6V drop (spec <0.2V). AC ripple: 450mV (spec <100mV). Correct repair?','["Only replace alternator","High ripple = failed diode pack; high drop = bad cable. Replace both","Clean battery terminals and retest","Replace battery"]'::jsonb,1,'AC ripple >400mV = diode failure. Cable drop means reduced output is not reaching battery.' FROM public.challenges WHERE slug='alternator-charging' ON CONFLICT DO NOTHING;

INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'Multiple U-codes after a jump-start. Most important first step?','["Replace ECM — likely damaged","Check battery voltage and all fuses/fusible links first","Perform CAN bus resistance test immediately","Replace all modules with U-codes"]'::jsonb,1,'Confirm power supply first. Low battery or blown fuse causes multiple U-codes without damage.' FROM public.challenges WHERE slug='can-bus-u-codes-ram' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',1,'Battery/fuses OK. CAN bus resistance: 120 ohms (expected ~60). What does this indicate?','["CAN bus functioning correctly","One of two 120-ohm terminating resistors is open","Short between CAN-H and CAN-L","ECM has failed internally"]'::jsonb,1,'Two 120-ohm terminators in parallel = ~60 ohms. 120 ohms means only one is active.' FROM public.challenges WHERE slug='can-bus-u-codes-ram' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',2,'Open terminator found — BCM pin pushed back. Reseated, 60 ohms confirmed. U0100 still returns on TCM. Scope shows clean waveform. Remaining fault?','["ECM is damaged — replace it","Check for TCM-to-ECM message timeout — may need relearn after voltage event","Replace CAN bus wiring harness","Ignore the code"]'::jsonb,1,'Physical bus confirmed good. U0100 persisting often means config/security seed mismatch.' FROM public.challenges WHERE slug='can-bus-u-codes-ram' ON CONFLICT DO NOTHING;
