-- Bump every challenge to 10 questions (tier_order 0-9). The table's CHECK
-- constraint only allowed 0-2, so widen it first (found dynamically since
-- inline CHECK constraint names aren't guaranteed across environments).
DO $$
DECLARE r RECORD;
BEGIN
  FOR r IN
    SELECT conname FROM pg_constraint
    WHERE conrelid = 'public.questions'::regclass
      AND pg_get_constraintdef(oid) ILIKE '%tier_order%'
  LOOP
    EXECUTE format('ALTER TABLE public.questions DROP CONSTRAINT %I', r.conname);
  END LOOP;
END $$;
ALTER TABLE public.questions ADD CONSTRAINT questions_tier_order_check CHECK (tier_order BETWEEN 0 AND 9);

-- ============================================================
-- Top up the 8 existing challenges from 3 to 10 questions each
-- (tier_order 3-9), continuing each case's diagnostic narrative
-- into repair verification, relearn procedures, and comeback
-- prevention rather than just padding difficulty.
-- ============================================================

-- p0171-lean-bank1 (Toyota Camry 2.5L, Fuel)
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'MAF replaced. Before road-testing, what should be done to ensure the ECM relearns correctly?','["Disconnect the battery or use a scan tool to reset adaptive fuel trims/idle relearn","Nothing — the ECM adapts automatically within seconds","Manually set fuel trims to zero in the ECM","Replace the PCM"]'::jsonb,0,'Clearing adaptive fuel trim memory after a sensor replacement lets the ECM relearn from a clean baseline.' FROM public.challenges WHERE slug='p0171-lean-bank1' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'Post-repair test drive: idle LTFT +3%, cruise LTFT +2%, WOT STFT +1%. Customer says hesitation is gone. Correct next step?','["Declare repair complete — trims are within normal range and symptom resolved","Replace the O2 sensor as a precaution","Keep driving another 200 miles before closing the RO","Reflash the ECM"]'::jsonb,0,'Trims within a normal ±10% band plus resolved symptom confirms the repair.' FROM public.challenges WHERE slug='p0171-lean-bank1' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',5,'Two weeks later, MIL is on again with P0171 pending. Idle: LTFT +6%, STFT +8%, no smoke smell, EVAP monitor incomplete. Most efficient next step?','["Replace the MAF again — it must have failed a second time","Smoke test the intake and EVAP system since a slow leak could still be masked at idle","Immediately replace the fuel pump","Tell the customer this is normal, no action needed"]'::jsonb,1,'Mild trims with an incomplete EVAP monitor point toward a secondary slow leak, not a repeat MAF failure.' FROM public.challenges WHERE slug='p0171-lean-bank1' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'Smoke test finds the EVAP purge line disconnected during the MAF job was never fully reseated. After reseating, LTFT returns to +2%. What documentation step prevents this becoming a comeback again?','["No documentation needed, it''s fixed","Note on the RO that all disconnected vacuum/EVAP lines were verified reseated after intake work","Just tell the customer verbally","File the code as unrelated"]'::jsonb,1,'Documenting the verification step creates accountability for connections disturbed during other work.' FROM public.challenges WHERE slug='p0171-lean-bank1' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'A different Camry arrives with an identical complaint and P0171. A tech skips live data and replaces the MAF immediately based on the last job. Root cause turns out to be a cracked intake boot. What principle was violated?','["None — MAF is always the fix for P0171","Diagnose using data before replacing parts, rather than pattern-matching to a prior unrelated repair","The tech should have checked spark plugs instead","The customer should have specified the exact cause"]'::jsonb,1,'Every P0171 needs its own data-driven diagnosis — the cause varies vehicle to vehicle.' FROM public.challenges WHERE slug='p0171-lean-bank1' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'On the intake boot job, what''s the correct way to verify the repair beyond just clearing codes?','["Smoke test the repaired boot under vacuum, confirm trims normalize across idle/cruise/WOT, and complete a drive cycle","Clear codes and hand back the keys immediately","Only check for smoke at idle","Replace the O2 sensor regardless"]'::jsonb,0,'A full verification confirms both the physical repair and that the ECM has settled to normal trims.' FROM public.challenges WHERE slug='p0171-lean-bank1' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'Overall, what''s the correct diagnostic sequence for any P0171 lean code, in order?','["Replace MAF, then O2 sensor, then check for leaks","Confirm the code with live data, interpret the trim pattern to localize the leak, smoke test to pinpoint it, repair, then verify with a drive cycle","Replace whichever sensor is cheapest first","Reflash the ECM before doing anything else"]'::jsonb,1,'Data first, then localization, then repair, then verification — the general lean-code methodology.' FROM public.challenges WHERE slug='p0171-lean-bank1' ON CONFLICT DO NOTHING;

-- lh-low-beam-open (Ford F-250, Electrical)
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'Repair complete, low beam works. What else should be checked given the shared harness routing nearby?','["Check RH low beam and both high beams for proper operation","No further checks needed","Only check the fuse box","Check unrelated systems like the radio"]'::jsonb,0,'Nearby circuits sharing routing or connectors are worth a quick check after any harness repair.' FROM public.challenges WHERE slug='lh-low-beam-open' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'While verifying, the DRL function is now flickering intermittently on the same side. Most likely cause?','["Unrelated coincidence — ignore it","The splice/repair point may have introduced a loose connection affecting a shared feed circuit","The DRL module has failed","Replace the headlamp assembly"]'::jsonb,1,'A fresh splice is the first suspect for a new symptom appearing right after that repair.' FROM public.challenges WHERE slug='lh-low-beam-open' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',5,'Wiggle test at the repair splice reproduces the flicker. What''s the correct permanent repair method for a weather-exposed engine bay splice?','["Twist wires together and wrap with electrical tape","Solder or use a heat-shrink-rated crimp connector, then heat-shrink seal it","Use a wire nut","Bypass with an inline fuse holder"]'::jsonb,1,'A sealed, heat-shrink splice resists vibration and moisture far better than tape or a twist splice.' FROM public.challenges WHERE slug='lh-low-beam-open' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'After the proper splice repair, what test confirms long-term reliability, not just immediate function?','["Visual inspection only","Voltage drop test under load plus a wiggle test across the full repair while monitoring for fluctuation","Just turn the lights on and off once","Check fuse rating only"]'::jsonb,1,'Vibration-sensitive faults only show up under a dynamic test, not a static check.' FROM public.challenges WHERE slug='lh-low-beam-open' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'What''s the most useful root cause note for the RO, for warranty/comeback tracking?','["''Fixed lights''","''Open circuit — chafed/pinched wire between BCM and LH low beam connector; repaired with heat-shrink splice; verified voltage drop <0.1V and no flicker on wiggle test''","''Bulb was bad''","''Unknown cause, cleared codes''"]'::jsonb,1,'Specific root cause and verification data protects both the shop and the customer later.' FROM public.challenges WHERE slug='lh-low-beam-open' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'What test method best catches a vibration-sensitive short/open before releasing the vehicle?','["Static voltage check only, key on engine off","Wiggle/vibration test while monitoring voltage or continuity live, flexing the harness through its full range of motion","Just drive it around the block once","Check the battery voltage"]'::jsonb,1,'Intermittent faults need to be provoked under test conditions to be caught reliably.' FROM public.challenges WHERE slug='lh-low-beam-open' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'What''s the correct general diagnostic sequence for any ''open circuit, no light'' complaint with a good fuse and bulb?','["Replace the switch first","Verify power at the bulb connector energized, work backward toward the source, confirm ground side, repair, then voltage-drop test under load","Replace the entire harness","Swap the BCM"]'::jsonb,1,'Working backward from the symptom point toward the source is the standard open-circuit method.' FROM public.challenges WHERE slug='lh-low-beam-open' ON CONFLICT DO NOTHING;

-- p0401-egr-flow (Peterbilt 389 Paccar MX-13, Diesel/Emissions)
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'EGR cooler is confirmed failed internally (coolant residue found in the EGR passages). What must be done before replacing the cooler?','["Just bolt in the new cooler","Pressure test the cooling system for internal leaks and check coolant level/condition","Skip the coolant check, only diesel matters","Replace the turbocharger"]'::jsonb,1,'A failed EGR cooler often signals a broader cooling system issue worth confirming first.' FROM public.challenges WHERE slug='p0401-egr-flow' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'After EGR cooler replacement, what must be verified regarding coolant before the truck leaves the shop?','["Nothing, the system is sealed","Properly bleed air from the cooling system per OEM procedure and check for external leaks at the new fittings","Only check oil level","Fill with water instead of coolant temporarily"]'::jsonb,1,'Trapped air or a leaking fitting on the new cooler would cause a repeat failure quickly.' FROM public.challenges WHERE slug='p0401-egr-flow' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',5,'New cooler installed and bled, EGR delta pressure now reads 2.6 inH2O (in spec). What confirms full readiness before returning the truck?','["Just clear the code and send it","Clear codes and complete an EGR monitor drive cycle so onboard diagnostics confirm the system stays in spec, not just one snapshot","Disconnect the battery permanently","Force the monitor to ''pass'' in the scan tool"]'::jsonb,1,'A single good reading isn''t the same as the monitor confirming stability across a drive cycle.' FROM public.challenges WHERE slug='p0401-egr-flow' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'Two days later, the fleet reports the same P0401. EGR flow now reads normal, but a new low-coolant code is present. Most likely connection?','["Unrelated — EGR failed again independently","A slow coolant leak, possibly from the new cooler installation, is allowing air into the cooling passages and disrupting flow readings","The driver used the wrong fuel","The DPF needs replacement"]'::jsonb,1,'A slow leak introducing air can intermittently disrupt EGR cooler flow/temperature behavior.' FROM public.challenges WHERE slug='p0401-egr-flow' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'A loose hose clamp at the new cooler''s coolant fitting is found causing the slow leak. What repair-quality step should have caught this the first time?','["A post-repair cooling system pressure test to confirm no leaks before releasing the vehicle","Nothing could have caught it","Torquing the EGR valve bolts tighter","Replacing the thermostat"]'::jsonb,0,'A pressure test after any cooling system work catches slow leaks before they become repeat visits.' FROM public.challenges WHERE slug='p0401-egr-flow' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'For heavy-duty EGR cooler replacements generally, what''s the correct verification sequence after the repair?','["Bleed cooling system, pressure test for leaks, verify EGR flow data in spec, clear codes, run drive cycle, recheck for code return","Clear codes and road test immediately","Only check EGR valve movement","Skip verification if the part is new"]'::jsonb,0,'Each step catches a different failure mode — skipping any one leaves a gap.' FROM public.challenges WHERE slug='p0401-egr-flow' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'What generalizable lesson does this case teach about recurring EGR flow codes on diesels?','["Always replace the EGR valve first regardless of data","A flow restriction and internal cooler coolant leakage can produce similar P0401 symptoms — confirm with a cooling system pressure test, especially when a code returns after a fix","EGR codes are always caused by the sensor","Ignore recurring EGR codes if the truck still runs"]'::jsonb,1,'Distinguishing a mechanical restriction from a coolant-related fault avoids repeat comebacks.' FROM public.challenges WHERE slug='p0401-egr-flow' ON CONFLICT DO NOTHING;

-- 6-7-balance-rates (Ford 6.7 Powerstroke, Diesel/Fuel)
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'Leak-off test performed: Cyl 1-8 return flow all within spec except Cyl 5, which is roughly double the others. What does this indicate?','["Cyl 5 injector has excessive internal leakage, contributing to reduced rail pressure","Cyl 5 is not connected","Normal variation, ignore it","The HPFP is fine, ignore rail pressure"]'::jsonb,0,'Elevated leak-off on one cylinder points to that injector''s internal wear as a rail pressure drain.' FROM public.challenges WHERE slug='6-7-balance-rates' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'Cyl 5 injector replaced. Rail pressure now 4550 PSI at idle (in spec), balance rates all within ±1.5. Correct next step?','["Hand back keys immediately","Clear codes, run an idle stability check and road test to confirm smooth operation and no return of rough idle/white smoke","Replace the turbo as a precaution","Skip verification since bench numbers look good"]'::jsonb,1,'Bench numbers alone don''t confirm real-world drivability — a road test does.' FROM public.challenges WHERE slug='6-7-balance-rates' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',5,'During the road test, cold-start white smoke briefly returns but clears within 10 seconds and doesn''t recur. Is this a fault?','["Yes, immediately fail the vehicle and replace more injectors","Brief cold-start smoke that clears quickly can be within normal range as combustion stabilizes — compare against a known-good baseline before condemning parts","It always means head gasket failure","Replace the glow plugs regardless"]'::jsonb,1,'Not every transient cold-start symptom is a defect — context and baseline comparison matter.' FROM public.challenges WHERE slug='6-7-balance-rates' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'Customer wants to know why 3 injectors failed near the same time. Most likely underlying cause worth investigating?','["Pure coincidence, no investigation needed","Fuel quality/contamination or a failing fuel filter/lift pump upstream, since clustered failures often point to a systemic supply issue","The batteries are weak","The EGR valve caused this"]'::jsonb,1,'Multiple simultaneous injector failures usually share a root cause upstream, not independent random wear.' FROM public.challenges WHERE slug='6-7-balance-rates' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'Fuel filter inspection shows heavy contamination and water in the water separator. What should be done in addition to replacing the fuel filter?','["Nothing else needed","Drain and inspect the fuel tank, check for the contamination source, and consider a system flush to protect the new injectors and HPFP","Replace the turbo","Reflash the ECM only"]'::jsonb,1,'Replacing the filter without addressing the tank risks recontaminating the new parts immediately.' FROM public.challenges WHERE slug='6-7-balance-rates' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'What RO documentation best protects against a comeback/warranty dispute for a triple-injector repair like this?','["''Replaced injectors''","Balance rate and rail pressure readings before/after, leak-off test results, root cause (fuel contamination), and post-repair verification data all recorded","No documentation needed if the truck runs","Just the parts invoice"]'::jsonb,1,'Data-backed documentation is what actually settles a warranty dispute later.' FROM public.challenges WHERE slug='6-7-balance-rates' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'What''s the correct generalized diagnostic sequence for diesel injector balance rate complaints?','["Replace all injectors immediately","Pull balance rates to isolate suspect cylinders, confirm with leak-off/rail pressure data, investigate root cause before replacing parts, then verify with a full drive cycle","Only check compression","Replace the ECM"]'::jsonb,1,'Isolate, confirm, investigate root cause, repair, verify — in that order.' FROM public.challenges WHERE slug='6-7-balance-rates' ON CONFLICT DO NOTHING;

-- voltage-drop-no-crank (Chevy Silverado 5.3L, Automotive/Electrical)
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'A corroded ground strap between engine and frame is found, adding resistance as it flexes. Voltage drop under cranking load reads 0.35V (spec <0.2V). Correct repair?','["Add dielectric grease and leave it","Clean or replace the ground strap and terminals, then retest voltage drop under load","Bypass with a jumper wire permanently","Ignore it since it''s ''only'' a ground"]'::jsonb,1,'A ground path fault is repaired and verified the same way as a power-side fault.' FROM public.challenges WHERE slug='voltage-drop-no-crank' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'After replacing the ground strap, positive and negative side voltage drops read 0.08V and 0.03V — within spec. What''s the final verification step?','["None needed","Multiple cold-crank cycles while monitoring voltage drop to confirm the fix holds under repeated real-world starting conditions","Just start it once","Check radio presets"]'::jsonb,1,'One good crank doesn''t rule out a marginal connection that fails intermittently.' FROM public.challenges WHERE slug='voltage-drop-no-crank' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',5,'The truck sat for 3 weeks before the original complaint started. What''s a likely contributing factor worth checking on any vehicle with this history?','["None, unrelated","Battery health/state of charge and terminal corrosion from extended sitting, which can accelerate corrosion at high-resistance points","Transmission fluid level","Tire pressure"]'::jsonb,1,'Extended sitting is a common accelerant for corrosion-related starting circuit faults.' FROM public.challenges WHERE slug='voltage-drop-no-crank' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'Battery load test shows 78% of rated CCA. Correct call?','["It''s fine, leave it","Recommend replacement — a marginal battery combined with any remaining system resistance increases risk of a repeat no-crank complaint","Charge it once and reinstall, no further action","The battery is unrelated to the starting circuit"]'::jsonb,1,'A marginal battery is itself a latent cause of recurring starting complaints, even after wiring is fixed.' FROM public.challenges WHERE slug='voltage-drop-no-crank' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'What''s the best way to explain this repair to the customer, given two separate faults were found?','["''We fixed it, it works now''","Explain both faults found, the data supporting each, and the battery test result showing a third contributing factor, tying it to why symptoms can recur without full diagnosis","No explanation needed, just bill for parts","Blame the previous shop only"]'::jsonb,1,'Transparent, data-backed explanations build trust and justify diagnostic time.' FROM public.challenges WHERE slug='voltage-drop-no-crank' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'What general principle does this case illustrate about no-crank/slow-crank diagnosis?','["Always replace the starter first","Both the positive and ground paths must be voltage-drop tested under load, since a fixed fault can mask a second one until it also fails","Only the battery matters","Voltage drop testing is unnecessary if the battery is new"]'::jsonb,1,'A starting circuit has two paths, and either can independently cause the same symptom.' FROM public.challenges WHERE slug='voltage-drop-no-crank' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'What''s the correct generalized diagnostic sequence for any slow-crank/no-crank complaint with good battery voltage at rest?','["Replace the starter immediately","Load test the battery, voltage-drop test the full positive and ground paths under cranking load, repair the highest-resistance points, and re-verify with repeated cold-crank cycles","Only check the ignition switch","Replace the PCM"]'::jsonb,1,'Static voltage checks miss under-load resistance faults entirely — always test under cranking load.' FROM public.challenges WHERE slug='voltage-drop-no-crank' ON CONFLICT DO NOTHING;

-- p0300-misfire-accord (Honda Accord 2.4L, Automotive/Fuel)
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'Cylinder 2 head is removed for inspection. What visual finding would confirm the running-compression diagnosis?','["A cracked piston","Carbon buildup or a visibly worn/burned intake valve seat/face on cylinder 2 that doesn''t match the other cylinders","A bent connecting rod","A leaking head gasket to the coolant jacket"]'::jsonb,1,'The running-compression test pointed to a valve not seating — a worn/burned seat confirms it visually.' FROM public.challenges WHERE slug='p0300-misfire-accord' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'Valve is confirmed burned. What must be checked on the valve seat/guide during machine work for a lasting repair?','["Nothing, just replace the valve","Valve seat concentricity/seal and guide clearance must be verified/machined to spec, not just a valve swap","Only check the valve spring color","Replace the timing chain regardless"]'::jsonb,1,'A new valve on a poorly reconditioned seat will burn again.' FROM public.challenges WHERE slug='p0300-misfire-accord' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',5,'After the valve job, what test confirms proper seating across all cylinders before reassembly?','["None needed, trust the machine shop","A leak-down test on each cylinder to confirm valve seal and ring seal are within spec","Just measure valve length","Check spark plug gap"]'::jsonb,1,'Leak-down testing directly measures seal quality, which visual inspection alone can''t guarantee.' FROM public.challenges WHERE slug='p0300-misfire-accord' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'Reassembled and running. Idle is smooth, but P0302 returns as a pending code after 50 miles, no misfire felt. What should be checked first?','["Assume the valve job failed and pull the head again","Check the stored misfire counter with freeze frame data — a single low-count pending code right after repair may not indicate a new failure","Replace the ECM","Ignore it, pending codes never matter"]'::jsonb,1,'Freeze frame and misfire counts distinguish a settling event from an actual repeat failure.' FROM public.challenges WHERE slug='p0300-misfire-accord' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'Freeze frame shows the pending misfire occurred at the very next cold start after repair, at 1 count, and hasn''t recurred in 200 miles since. Correct conclusion and action?','["Immediately warranty the valve job as failed","Likely a one-time post-repair settling event; verify with another drive cycle before taking further action","Replace all spark plugs again","Tell the customer to ignore the check engine light forever"]'::jsonb,1,'A single isolated count with no recurrence is consistent with settling, not a real defect.' FROM public.challenges WHERE slug='p0300-misfire-accord' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'The pending code clears on its own after another drive cycle with no misfires. What should be documented for this repeat customer visit?','["Nothing, delete the record","The pending code event, freeze frame data reviewed, no misfire counts since, and monitor cleared","Just say ''no problem found''","Blame the customer''s driving"]'::jsonb,1,'A documented, data-backed non-event protects both shop and customer if it resurfaces.' FROM public.challenges WHERE slug='p0300-misfire-accord' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'What''s the correct generalized diagnostic sequence for a single persistent cylinder misfire that survives a coil swap?','["Replace spark plugs and hope","Coil swap to rule out ignition, compare cranking vs running compression to catch valve-seating issues, injector/fuel test, confirm mechanical findings, then verify with leak-down and a drive cycle","Replace the ECM immediately","Always assume it''s a bad injector"]'::jsonb,1,'Running compression catches valve-seating faults that a normal cranking compression test misses entirely.' FROM public.challenges WHERE slug='p0300-misfire-accord' ON CONFLICT DO NOTHING;

-- alternator-charging (Honda Civic 1.5T, Automotive/Electrical)
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'New alternator and repaired B+ cable installed. What should be measured to confirm the repair is complete?','["Just visually inspect the belt","Re-test charging voltage under no-load and full-load, B+ to battery voltage drop, and AC ripple — all should now be within spec","Only check the battery terminals","Nothing further needed once parts are installed"]'::jsonb,1,'Every value that was out of spec originally needs to be re-measured, not just visually confirmed.' FROM public.challenges WHERE slug='alternator-charging' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'Post-repair: 14.4V at idle no-load, 13.9V under full load, cable drop 0.08V, AC ripple 45mV. What''s the verdict?','["Still failing, replace alternator again","All values are within spec — repair confirmed successful","Battery needs replacement now","Serpentine belt needs replacing"]'::jsonb,1,'All four measured values now sit comfortably within normal spec.' FROM public.challenges WHERE slug='alternator-charging' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',5,'Customer asks why the alternator failed. What''s the correct explanation of the diode pack failure that was found?','["Diodes don''t affect charging, only voltage regulation does","A failing diode causes increased AC ripple riding on the DC output, which can also gradually stress the battery before a warning light ever triggers","Diode failure is caused by tire pressure","It has nothing to do with the ripple reading"]'::jsonb,1,'Rising AC ripple is a classic early sign of rectifier diode degradation.' FROM public.challenges WHERE slug='alternator-charging' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'The battery is 4 years old and was subjected to months of marginal charging before repair. What should be checked/recommended?','["Nothing, the battery is fine automatically","Load test the battery — prolonged undercharging can shorten battery life and it may need replacement even though it currently starts the car","Replace the battery regardless of test results, always","Ignore the battery, only the alternator matters"]'::jsonb,1,'A history of marginal charging is a real reason to specifically test the battery, not assume it''s fine.' FROM public.challenges WHERE slug='alternator-charging' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'Battery load tests at 65% of rated capacity. What''s the correct recommendation and reasoning to the customer?','["Say nothing, let them find out later","Recommend battery replacement now, explaining the marginal charging period likely degraded it and a weak battery risks a repeat complaint","Tell them to just keep jump-starting it","Recommend replacing the alternator again"]'::jsonb,1,'Explaining the causal link between the old fault and the battery''s condition justifies the recommendation.' FROM public.challenges WHERE slug='alternator-charging' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'What data points should be documented on the RO to fully support this repair?','["''Replaced alternator''","Before/after voltage, load amps, cable drop, AC ripple readings, plus battery load test result and reasoning for the replacement recommendation","No documentation needed","Just the part numbers"]'::jsonb,1,'Full before/after data is what makes the diagnosis and recommendation defensible.' FROM public.challenges WHERE slug='alternator-charging' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'What''s the correct generalized diagnostic sequence for a charging system complaint (battery light, weak charge)?','["Replace the alternator immediately","Test charging voltage at idle and under load, voltage-drop test the B+ and ground cables, check AC ripple for diode issues, and load test the battery","Only check the serpentine belt","Only replace the battery"]'::jsonb,1,'Alternator, cabling, and battery can each independently contribute — all should be verified.' FROM public.challenges WHERE slug='alternator-charging' ON CONFLICT DO NOTHING;

-- can-bus-u-codes-ram (Ram 2500 6.7 Cummins, Diesel/Network)
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'The TCM is checked for a stored ''lost communication'' timestamp. It aligns exactly with the jump-start event. What does this suggest?','["The TCM is permanently damaged","The voltage spike/drop during the jump-start likely caused a momentary communication dropout the TCM latched as a fault, not an ongoing physical problem","The CAN bus wiring is still faulty","The ECM needs replacement"]'::jsonb,1,'A timestamp matching a known voltage event strongly suggests a latched historical fault, not a live one.' FROM public.challenges WHERE slug='can-bus-u-codes-ram' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'Correct procedure to clear a latched communication fault after confirming the physical bus is healthy?','["Replace the TCM regardless","Clear the DTC, cycle the key, and run a drive cycle to confirm the code doesn''t return now that the terminator is fixed","Disconnect the battery for a week","Reflash all modules"]'::jsonb,1,'Clearing and re-verifying confirms whether the fault was truly latched versus still active.' FROM public.challenges WHERE slug='can-bus-u-codes-ram' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',5,'After the drive cycle, U0100 does not return and all modules communicate normally. What final check confirms the whole vehicle network is healthy?','["Nothing further needed","A full system scan across all modules to check for any other stored or pending U-codes indicating a broader issue","Only check the radio","Only check modules that had power during the jump-start"]'::jsonb,1,'A full scan catches issues in modules that weren''t the original focus of the complaint.' FROM public.challenges WHERE slug='can-bus-u-codes-ram' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'Full scan comes back clean. What advice prevents recurrence on future jump-starts?','["None needed","Use proper jump-starting procedure (correct polarity, engine off during connection, or a jump box with voltage-spike protection) to avoid transients that can cause module faults","Always disconnect the battery before any jump-start","Jump-starts never cause electronic issues"]'::jsonb,1,'Correct jump-start technique reduces the voltage transients that caused this exact fault.' FROM public.challenges WHERE slug='can-bus-u-codes-ram' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'If the terminating resistor had NOT been the issue (normal ~60 ohms from the start), what would be the next step for multiple U-codes?','["Assume it''s unfixable and replace the whole harness","Check CAN-H and CAN-L for shorts to power/ground and opens using a scope or DMM at multiple points, since normal resistance rules out a terminator but not a partial short","Replace all modules one by one","Ignore the codes if the truck still runs"]'::jsonb,1,'Normal bus resistance narrows the fault to wiring integrity issues rather than a terminator.' FROM public.challenges WHERE slug='can-bus-u-codes-ram' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'What RO documentation best explains this repair for warranty/comeback purposes?','["''Fixed electrical issue''","Root cause (open CAN terminator from a pushed-back BCM pin), resistance readings before/after, and confirmation the U0100 code was a latched jump-start event that cleared after physical repair and drive cycle","''Cleared codes, no issue found''","No documentation, just close the RO"]'::jsonb,1,'This level of detail explains both the physical fix and the residual code behavior.' FROM public.challenges WHERE slug='can-bus-u-codes-ram' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'What''s the correct generalized diagnostic sequence for multiple U-codes on a network bus?','["Replace the module with the most codes first","Rule out power/ground first, check bus resistance for terminator faults, scope for shorts/opens if resistance is normal, distinguish latched from active faults, repair, then confirm with a drive cycle and full scan","Always replace the ECM","Ignore U-codes if the vehicle starts"]'::jsonb,1,'This sequence separates power issues, physical bus faults, and latched history from each other.' FROM public.challenges WHERE slug='can-bus-u-codes-ram' ON CONFLICT DO NOTHING;

-- ============================================================
-- 3 new challenges, filling the Drivetrain domain gap and the
-- unused 'ro' (repair order) challenge type, 10 questions each.
-- ============================================================

INSERT INTO public.challenges (slug,title,type,specialty,xp_reward,description,tags) VALUES
  ('tcc-shudder-diagnosis','TCC Shudder — Torque Converter Clutch Diagnosis','component','Automotive',130,'2015 Toyota Camry 2.5L, 6-speed automatic. Vibration/shudder felt through the seat between 45-55 mph under light throttle, most noticeable when warm.',ARRAY['Transmission','TCC','Torque Converter']),
  ('p242f-dpf-regen-failure','P242F — DPF Regeneration Failure, High Soot Load','dtc','Diesel',140,'2017 Ram 3500 6.7 Cummins. DPF lamp on, reduced power mode, P242F stored. Highway driving has dropped off in favor of mostly short city trips.',ARRAY['DPF','Emissions','Regen','Cummins']),
  ('ro-awd-vibration-comeback','Repair Order — AWD Vibration Comeback Diagnosis','ro','Automotive',120,'2019 Subaru Outback AWD. Another shop replaced two tires for a highway-speed vibration; it returned within a week. Back for a proper root-cause diagnosis.',ARRAY['AWD','Driveline','Repair Order','Comeback'])
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.challenge_domains (challenge_id,domain) SELECT id,'Drivetrain'::public.skill_domain FROM public.challenges WHERE slug='tcc-shudder-diagnosis' ON CONFLICT DO NOTHING;
INSERT INTO public.challenge_domains (challenge_id,domain) SELECT id,'Emissions'::public.skill_domain FROM public.challenges WHERE slug='p242f-dpf-regen-failure' ON CONFLICT DO NOTHING;
INSERT INTO public.challenge_domains (challenge_id,domain) SELECT id,'Drivetrain'::public.skill_domain FROM public.challenges WHERE slug='ro-awd-vibration-comeback' ON CONFLICT DO NOTHING;

-- tcc-shudder-diagnosis
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'TCC shudder that appears only when warm, under light cruise load, most closely resembles which condition?','["A wheel balance issue","Torque converter clutch engagement/slip shudder — a classic symptom of TCC apply-related friction or fluid issues","A bad spark plug","Low tire pressure"]'::jsonb,1,'Speed and load-specific shudder when warm is textbook TCC apply shudder.' FROM public.challenges WHERE slug='tcc-shudder-diagnosis' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',1,'What''s the first non-invasive check before suspecting internal transmission wear?','["Tear down the transmission","Check transmission fluid level, condition, and confirm the correct fluid type/spec was used in the last service","Replace the torque converter immediately","Replace the engine mounts"]'::jsonb,1,'Fluid condition and correct spec is the cheapest, fastest first check.' FROM public.challenges WHERE slug='tcc-shudder-diagnosis' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',2,'Fluid is the correct type and level is right, but has a slightly burnt smell and darker color than normal. What does this suggest?','["Nothing of concern","Possible friction material degradation or overheating history, consistent with TCC clutch wear","The engine oil is contaminated","The coolant is low"]'::jsonb,1,'Burnt-smelling, dark ATF is a common indicator of clutch material breakdown or heat history.' FROM public.challenges WHERE slug='tcc-shudder-diagnosis' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'Scan tool live data during a test drive shows TCC slip speed of 180 RPM sustained at cruise (spec: near 0 RPM once locked). What does this confirm?','["The TCC is not fully locking/engaging, causing the shudder — consistent with worn friction material or a solenoid issue","The engine is misfiring","The wheel speed sensors are miscalibrated","This is completely normal"]'::jsonb,0,'Sustained slip well above spec directly confirms the TCC isn''t achieving full lockup.' FROM public.challenges WHERE slug='tcc-shudder-diagnosis' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'TCC apply pressure is checked and reads low compared to spec at the commanded duty cycle. What are the two most likely culprits to investigate next?','["Spark plugs and ignition coils","TCC solenoid performance and valve body wear/contamination at the TCC regulator circuit","Wheel bearings and CV joints","Alternator and battery"]'::jsonb,1,'Low apply pressure at the correct duty cycle points to the solenoid or the valve body circuit feeding it.' FROM public.challenges WHERE slug='tcc-shudder-diagnosis' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',5,'TCC solenoid resistance tests within spec, but the valve body has visible varnish/sludge in the TCC circuit passages. Correct next step?','["Replace the engine","Service or replace the valve body (or have it rebuilt) and perform a full fluid and filter change","Ignore it and just top off fluid","Replace the torque converter only, valve body unrelated"]'::jsonb,1,'A good solenoid with a fouled valve body still needs the valve body addressed.' FROM public.challenges WHERE slug='tcc-shudder-diagnosis' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'After valve body service and fluid/filter change, shudder is much reduced but a faint shudder remains only right at initial TCC lock-up. What does this suggest?','["The repair failed completely","The torque converter''s internal clutch friction material itself may be worn/glazed, requiring converter replacement rather than just valve body service","Wheel alignment is off","The issue is unrelated and pre-existing"]'::jsonb,1,'A remaining lock-up-only shudder after fixing the hydraulic circuit points to the friction material itself.' FROM public.challenges WHERE slug='tcc-shudder-diagnosis' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'Torque converter is replaced along with a full fluid exchange. What must be done regarding TCM adaptive values before the final road test?','["Nothing, it adapts automatically with no reset needed","Reset/clear the transmission adaptive learning values via scan tool so the TCM relearns shift and TCC apply pressures for the new converter, then run a relearn drive cycle","Reflash the ECM only","Disconnect the battery for a month"]'::jsonb,1,'Old adaptive values tuned for the worn converter would misapply pressure on the new one.' FROM public.challenges WHERE slug='tcc-shudder-diagnosis' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'Post-repair test drive: TCC slip speed now under 15 RPM at cruise, no shudder across multiple warm-up cycles. What final step should close out this repair?','["None, it''s done","Confirm no shudder across varied speeds/loads while warm, verify no new codes stored, and document baseline slip speed for future reference","Just check the fluid level one more time","Replace the transmission mount as well, unrelated but ''just in case''"]'::jsonb,1,'Broad condition testing plus a documented baseline gives a clean, defensible close-out.' FROM public.challenges WHERE slug='tcc-shudder-diagnosis' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'What''s the correct generalized diagnostic sequence for a TCC shudder complaint?','["Replace the transmission immediately","Verify fluid condition/type first, confirm TCC slip via live data, check apply pressure and solenoid/valve body health, address root cause in order of invasiveness, then relearn adaptive values and verify with a drive cycle","Always replace the torque converter first regardless of data","Ignore shudder complaints since they''re subjective"]'::jsonb,1,'Least-invasive-first ordering avoids unnecessary converter replacement when a valve body service would fix it.' FROM public.challenges WHERE slug='tcc-shudder-diagnosis' ON CONFLICT DO NOTHING;

-- p242f-dpf-regen-failure
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'What does P242F (DPF soot load too high) most directly indicate?','["A fuel pressure fault","The diesel particulate filter has accumulated more soot than the system can safely manage without intervention","A transmission fault","A coolant leak"]'::jsonb,1,'The code is a direct soot-load threshold warning, not a component failure code by itself.' FROM public.challenges WHERE slug='p242f-dpf-regen-failure' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',1,'The customer''s driving pattern (mostly short city trips) is relevant because:','["It''s unrelated to DPF health","Short trips often don''t get the exhaust hot enough for long enough to complete passive/active regeneration, letting soot accumulate over time","Short trips only affect fuel economy","Short trips damage the turbocharger only"]'::jsonb,1,'Regen requires sustained exhaust temperature that short city trips rarely reach.' FROM public.challenges WHERE slug='p242f-dpf-regen-failure' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',2,'What should be checked with the scan tool before attempting any regen?','["Nothing, just start a forced regen immediately","Current soot load percentage and DPF differential pressure readings to confirm how severe the accumulation is","Tire pressure sensors","Radio settings"]'::jsonb,1,'Knowing the severity first determines whether a forced regen is even appropriate.' FROM public.challenges WHERE slug='p242f-dpf-regen-failure' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'Soot load reads 85% and differential pressure is elevated at idle. What''s the appropriate next step?','["Replace the DPF immediately without attempting regen","Attempt a scan-tool-commanded stationary forced regeneration, since soot load, while high, may still be low enough to burn off with an assisted regen","Tell the customer nothing can be done","Disconnect the DPF and drive without it"]'::jsonb,1,'A forced regen is the standard first attempt before considering filter replacement.' FROM public.challenges WHERE slug='p242f-dpf-regen-failure' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'During the forced regen, exhaust gas temperature fails to reach target. What are the likely contributing components to check?','["Wheel bearings","Post-injection fuel delivery for regen, EGT sensors, and the DOC upstream of the DPF, since any of these can prevent reaching regen temperature","Battery terminals","Cabin air filter"]'::jsonb,1,'Any of these three can independently prevent the exhaust from reaching regen temperature.' FROM public.challenges WHERE slug='p242f-dpf-regen-failure' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',5,'EGT sensor readings before/after the DOC show a smaller-than-expected temperature rise across it. What does this suggest?','["The DOC is functioning perfectly","The DOC may be contaminated or degraded, not generating enough exothermic reaction heat to support DPF regen","The DPF itself is the only problem","This is a normal reading"]'::jsonb,1,'A weak temperature rise across the DOC directly indicates reduced catalytic activity.' FROM public.challenges WHERE slug='p242f-dpf-regen-failure' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'DOC is found coated/contaminated. What must be checked as a root cause before simply replacing it?','["Nothing, just replace the DOC and move on","Check for excessive oil consumption/burning or fuel dilution issues that could be contaminating the DOC and would recontaminate a new one if unaddressed","Only check the tire tread","Replace the transmission"]'::jsonb,1,'Replacing a contaminated DOC without fixing the contamination source just repeats the failure.' FROM public.challenges WHERE slug='p242f-dpf-regen-failure' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'Oil consumption is confirmed above normal, with the crankcase filter contributing extra oil vapor into the intake. What repair addresses the root cause?','["Replace the DOC and DPF only, ignore the oil issue","Address the oil consumption source (e.g., replace crankcase ventilation filter/valve, inspect for related wear) in addition to DOC/DPF service","Just top off oil more frequently and ignore the smoke","Reflash the ECM only"]'::jsonb,1,'Leaving the oil source unaddressed guarantees the new emissions parts get recontaminated.' FROM public.challenges WHERE slug='p242f-dpf-regen-failure' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'After DOC/DPF service and addressing the oil consumption source, what verification sequence confirms the repair?','["None, just clear codes and hand back the keys","Perform a forced regen to confirm normal EGT rise across the DOC and successful soot burn-off, verify soot load drops to baseline, clear codes, and road test to confirm no return of reduced power mode","Only check DPF differential pressure once","Skip the regen since parts are new"]'::jsonb,1,'A full forced-regen verification confirms the whole chain is working, not just that parts were swapped.' FROM public.challenges WHERE slug='p242f-dpf-regen-failure' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'What advice should be given to the customer to prevent recurrence given their short-trip driving pattern?','["None needed, the repair is permanent regardless of driving habits","Periodically take longer highway trips (or manually initiate stationary regens per OEM guidance) since consistently short trips caused the original soot buildup","Avoid highway driving entirely","Remove the DPF permanently"]'::jsonb,1,'Their driving pattern was the original root cause, so it needs to change or be compensated for.' FROM public.challenges WHERE slug='p242f-dpf-regen-failure' ON CONFLICT DO NOTHING;

-- ro-awd-vibration-comeback
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'Given the vibration returned quickly after a tire replacement, what''s the correct first step before doing any new repair?','["Immediately replace the other two tires as well","Review the previous shop''s notes if available and gather detailed symptom info from the customer before assuming the same root cause","Assume the previous shop was wrong about everything","Skip straight to replacing the driveshaft"]'::jsonb,1,'Gathering context first avoids repeating a guess that already failed once.' FROM public.challenges WHERE slug='ro-awd-vibration-comeback' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',1,'Customer says the vibration is speed-related, increasing with speed, regardless of braking or turning. What does this pattern suggest?','["A brake issue","A rotating component out of balance or worn, such as a tire/wheel, driveshaft, or wheel bearing","A steering rack issue only","An engine mount issue"]'::jsonb,1,'Speed-proportional vibration independent of braking/turning points to a rotating component.' FROM public.challenges WHERE slug='ro-awd-vibration-comeback' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',2,'What''s the correct first diagnostic test for a speed-related vibration on an AWD vehicle?','["Replace the transmission","A road test to confirm and characterize the vibration, then a tire/wheel balance and runout check, since that''s the least invasive and most common cause","Replace the AWD transfer case immediately","Replace all four tires without testing"]'::jsonb,1,'Start with the least invasive, most statistically common cause before moving to the driveline.' FROM public.challenges WHERE slug='ro-awd-vibration-comeback' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'New tires balance out fine with no excessive runout. Vibration is still present at highway speed. What''s the next logical component to check on this AWD vehicle?','["The radio antenna","The driveshaft and center support bearing for wear, runout, or damage, since AWD vehicles have a rear driveshaft that''s a common vibration source often overlooked when focusing only on tires","The windshield wipers","The cabin air filter"]'::jsonb,1,'With tires ruled out, the driveshaft is the next most common speed-related vibration source on AWD.' FROM public.challenges WHERE slug='ro-awd-vibration-comeback' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'Driveshaft inspected — one of the two U-joints shows play when checked by hand with the shaft supported. What does this indicate?','["Normal wear, no action needed","A worn U-joint is a likely contributor to the vibration and should be replaced (or the driveshaft assembly, depending on design)","The transmission needs replacement","This is unrelated to vibration complaints"]'::jsonb,1,'Detectable play in a U-joint under no load is already beyond normal wear tolerance.' FROM public.challenges WHERE slug='ro-awd-vibration-comeback' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',5,'Why is it important to check the U-joint with the shaft supported and under no load, rather than just looking at it?','["It''s not important, visual is enough","Play/looseness in a U-joint can be subtle and only detectable by hand-checking for movement, since visual inspection alone often misses early-stage wear that still causes vibration at speed","Only a spin balance machine can detect U-joint wear","U-joints never wear out"]'::jsonb,1,'Early-stage U-joint wear is a tactile finding, not always a visible one.' FROM public.challenges WHERE slug='ro-awd-vibration-comeback' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'After replacing the driveshaft/U-joint, what should be checked given this is an AWD vehicle with a center differential/transfer case in the driveline?','["Nothing else, the repair is complete","Confirm all driveline components (differential fluid, transfer case) are in good condition and the new driveshaft is properly torqued and phased correctly, since improper installation can introduce a new vibration","Replace the transfer case regardless","Only check tire pressure again"]'::jsonb,1,'Incorrect driveshaft phasing is a common installation error that reintroduces vibration.' FROM public.challenges WHERE slug='ro-awd-vibration-comeback' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'Test drive after the repair shows the original vibration is gone. What should be documented on the RO to distinguish this from the previous shop''s incomplete repair?','["''Fixed vibration''","Root cause identified (worn U-joint on rear driveshaft), confirmed via hand-check with shaft supported, distinct from the tire imbalance addressed previously, plus post-repair road test confirmation","Nothing, just close the RO","Blame the customer for not returning sooner"]'::jsonb,1,'A specific root cause note explains why the first repair attempt didn''t resolve the complaint.' FROM public.challenges WHERE slug='ro-awd-vibration-comeback' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'The customer asks why the first shop''s tire replacement didn''t fix it. What''s the most professional and accurate explanation?','["''They were incompetent''","Tire imbalance can also cause speed-related vibration, so it was a reasonable first check, but there were two contributing factors here and only the tire was addressed — a full driveline inspection was needed to find the second cause","''It''s your fault for driving on bad tires''","Avoid the question entirely"]'::jsonb,1,'Acknowledging the first check was reasonable while explaining the missed second cause is both accurate and professional.' FROM public.challenges WHERE slug='ro-awd-vibration-comeback' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'What''s the correct generalized diagnostic sequence for a comeback vibration complaint after a previous repair didn''t resolve it?','["Assume the same fix will work if repeated","Re-verify the complaint firsthand, work from least to most invasive, check for multiple contributing causes rather than stopping at the first finding, repair, and document clearly to explain the difference from the prior attempt","Replace the entire drivetrain to be safe","Tell the customer nothing can be done"]'::jsonb,1,'Comebacks often mean a second, unaddressed cause exists alongside the first — keep looking, don''t stop at one finding.' FROM public.challenges WHERE slug='ro-awd-vibration-comeback' ON CONFLICT DO NOTHING;
