-- 020_three_new_challenges.sql
-- Adds Parasitic Draw (Electrical), P0420 Catalyst Efficiency (Emissions), and
-- U0101 No-Comm TCM (Network): 3 challenges x 10 questions, authored to the
-- distractor standard from migration 019 (same-system competing hypotheses only)
-- and validated for position distribution, length correlation, phrase frequency,
-- and throwaway patterns as required by CLAUDE.md.

INSERT INTO public.challenges (slug,title,type,specialty,xp_reward,description,tags) VALUES
  ('parasitic-draw-tahoe','Parasitic Draw — Battery Dead After Sitting','wiring','Automotive',140,'2016 Chevy Tahoe 5.3L. Battery is dead after sitting two days; battery and alternator both test good, and a new battery didn''t change anything.',ARRAY['Battery','Parasitic Draw','Body Electrical']),
  ('p0420-cat-efficiency','P0420 — Catalyst Efficiency Below Threshold','dtc','Automotive',120,'2014 Honda Civic 1.8L, 162k miles. MIL on with P0420 and no driveability complaint. Another shop already replaced both O2 sensors; the light was back within 300 miles.',ARRAY['Catalyst','O2 Sensors','Emissions']),
  ('u0101-no-comm-tcm','U0101 — Lost Communication With TCM','wiring','Automotive',150,'2018 Ford F-150 3.5L EcoBoost, 10R80. Truck is in limp mode with a wrench light, U0101 stored in several modules, and the scan tool gets no response from the TCM.',ARRAY['CAN Bus','U-Codes','TCM'])
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.challenge_domains (challenge_id,domain) SELECT id,'Electrical'::public.skill_domain FROM public.challenges WHERE slug='parasitic-draw-tahoe' ON CONFLICT DO NOTHING;
INSERT INTO public.challenge_domains (challenge_id,domain) SELECT id,'Emissions'::public.skill_domain FROM public.challenges WHERE slug='p0420-cat-efficiency' ON CONFLICT DO NOTHING;
INSERT INTO public.challenge_domains (challenge_id,domain) SELECT id,'Network'::public.skill_domain FROM public.challenges WHERE slug='u0101-no-comm-tcm' ON CONFLICT DO NOTHING;

-- parasitic-draw-tahoe
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'The battery tests good and charging output is normal, yet the truck goes flat over two days parked. What measurement establishes whether a parasitic draw exists?','["Resting voltage at the battery posts after the truck sits overnight", "Key-off current draw at the battery after the modules time out", "Specific gravity of each cell once the battery is recharged", "Voltage drop across the main fusible link with the key on"]'::jsonb,1,'A parasitic draw is confirmed by measuring key-off current after all modules have gone to sleep — voltage readings alone can''t separate a draw from a weak battery.' FROM public.challenges WHERE slug='parasitic-draw-tahoe' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',1,'Why is it important to wait 30-45 minutes after locking the vehicle before reading key-off draw on a late-model truck?','["The battery surface charge has to dissipate before current stabilizes", "The amp clamp needs that long to thermally stabilize on the cable", "Retained accessory power keeps the ignition circuit live that long", "Modules stay awake and drawing current until their sleep timers expire"]'::jsonb,3,'Modern vehicles keep modules awake for a timed period after key-off; a reading taken before they sleep shows a ''draw'' that''s really normal wake activity.' FROM public.challenges WHERE slug='parasitic-draw-tahoe' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',2,'After sleep, draw reads 620mA (spec below 50mA). What''s the least invasive way to localize which circuit carries it?','["Measure millivolt drop across each fuse and convert with the fuse chart", "Pull fuses one at a time until the meter falls, starting at the biggest", "Disconnect each module connector in turn and watch the reading", "Clamp each branch of the underhood harness with the inductive meter"]'::jsonb,0,'Reading millivolt drop across fuses identifies the live circuit without unplugging anything — pulling fuses or connectors wakes modules and resets the hunt.' FROM public.challenges WHERE slug='parasitic-draw-tahoe' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'Fuse F31 (10A, ''Amplifier/Radio'') shows 4.2mV across it; every other fuse reads near 0.0mV. What does this establish?','["The fuse itself has corroded and is adding series resistance", "That reading is inside meter noise; the draw sits on an unfused circuit", "Current is flowing in the amplifier/radio circuit while the truck sleeps", "A 10A fuse can''t pass enough current at 4.2mV to matter overnight"]'::jsonb,2,'Any steady millivolt drop across a fuse means current is flowing through that circuit; the fuse chart converts the reading to amps to match it against the measured draw.' FROM public.challenges WHERE slug='parasitic-draw-tahoe' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'The truck has an aftermarket amplifier under the rear seat. Its remote-turn-on wire is tapped into a constant 12V feed instead of a switched source. Why does this cause the draw?','["The tap corroded and leaks current through the insulation to ground", "The amp never receives a turn-off signal, so it idles powered all night", "Constant feeds carry ripple that keeps cycling the amp''s power supply", "The added load pulls the radio fuse''s rating down over repeated cycles"]'::jsonb,1,'The remote wire is what tells an amplifier to shut down; tied to constant power, the amp sits in its powered idle state around the clock and drains the battery.' FROM public.challenges WHERE slug='parasitic-draw-tahoe' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',5,'The amp''s remote wire is moved to a proper switched accessory source. What reading verifies the repair?','["Battery voltage recovering above 12.6V within a few minutes of the fix", "The amplifier powering off audibly the moment the key comes out", "Draw at the battery under 50mA immediately after locking the doors", "Draw settling under 50mA after the modules complete their sleep cycle"]'::jsonb,3,'The pass condition is the same measurement that failed: key-off draw within spec after module sleep — checked too early it reads falsely high.' FROM public.challenges WHERE slug='parasitic-draw-tahoe' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'Draw now reads 38mA. Two weeks later the truck is back — dead again, but only after sitting through a rainy weekend. Key-off draw in the dry shop reads 41mA. What''s the next diagnostic move?','["Repeat the fuse voltage-drop sweep in case a new circuit went live", "Recheck the amplifier wiring, since it was the last thing touched", "Wet-test it: soak the likely harness areas and re-measure the draw", "Move the clamp to the positive cable in case the negative path splits"]'::jsonb,2,'An in-spec reading in a dry shop doesn''t disprove a moisture-dependent fault; reproducing the wet condition while monitoring draw is how it gets caught.' FROM public.challenges WHERE slug='parasitic-draw-tahoe' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'With the rear body area soaked, draw jumps to 900mA and the fuse sweep points at the trailer-tow circuit. The 7-pin connector at the bumper is packed with mud and green corrosion. Why can this drain a battery only when wet?','["Wet corrosion forms a conductive path between 12V pins and ground", "Mud insulates the pins until water compresses it against the contacts", "Rain cooling the connector lowers its contact resistance sharply", "Water shorts the trailer brake signal into its return line downstream"]'::jsonb,0,'Dry corrosion conducts poorly, but once saturated it becomes an electrolytic bridge that leaks current from constant-power pins to ground until everything dries out.' FROM public.challenges WHERE slug='parasitic-draw-tahoe' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'Correct repair for the corroded 7-pin trailer connector on a truck that tows regularly?','["Pack the existing connector body with dielectric grease to displace the moisture", "Splice the constant-power pin out of service until towing season returns", "Fit a weather cap and re-route the pigtail loop so water drips clear of it", "Replace the connector, repair the damaged pigtail, and seal the harness entry"]'::jsonb,3,'Corroded terminals keep wicking moisture and regrowing; replacing the connector and sealing the entry is what restores a reliable circuit for regular towing.' FROM public.challenges WHERE slug='parasitic-draw-tahoe' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'The customer asks why two different problems caused the same dead-battery symptom in the same month. Best professional framing?','["The amp install most likely damaged the trailer-tow circuit while being routed", "Each fault was verified on its own; the second one only shows up in wet weather", "It''s really one problem \u2014 the amplifier draw overworked the trailer connector", "A battery weakened by repeated deep discharge invites failures, so expect more"]'::jsonb,1,'Two independently verified faults sharing one symptom is common in electrical work; explaining that the second was condition-dependent shows why it surfaced later, without guesswork.' FROM public.challenges WHERE slug='parasitic-draw-tahoe' ON CONFLICT DO NOTHING;

-- p0420-cat-efficiency
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'What comparison does the ECM use to set P0420 in the first place?','["The upstream O2 sensor''s switching speed measured against a factory rate", "Commanded air-fuel ratio against measured exhaust lambda at cruise", "Downstream O2 activity against upstream; a good cat damps the rear signal", "Catalyst inlet and outlet temperature rise during closed-loop cruise"]'::jsonb,2,'The catalyst monitor compares rear O2 sensor activity to the front; oxygen storage in a healthy catalyst keeps the rear signal flat while the front switches.' FROM public.challenges WHERE slug='p0420-cat-efficiency' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',1,'Why did replacing both O2 sensors fail to fix this P0420?','["The sensors were reporting accurately \u2014 the catalyst itself is degraded", "New sensors need a relearn before the monitor will accept them", "Aftermarket sensors switch too slowly to satisfy Honda''s catalyst monitor", "The heater circuits weren''t activated until a full drive cycle ran"]'::jsonb,0,'P0420 indicts the catalyst''s oxygen storage, not the sensors; when the sensors are working, replacing them changes nothing about the monitor''s comparison.' FROM public.challenges WHERE slug='p0420-cat-efficiency' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',2,'Live data at 2500 RPM steady: front O2 switching 0.1-0.9V rapidly; rear O2 mirroring it at 0.2-0.8V. What does the rear signal show?','["Normal behavior while the monitor is still warming the catalyst up", "The catalyst is storing little oxygen, so the rear sensor sees raw swings", "A rear sensor grounding issue that''s amplifying its output swing", "Exhaust pulsations reaching the rear sensor through a hollowed-out muffler"]'::jsonb,1,'A rear O2 that mirrors the front means exhaust is passing through the catalyst chemically unchanged — its oxygen storage capacity is gone.' FROM public.challenges WHERE slug='p0420-cat-efficiency' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'Before condemning the catalyst on a 162k-mile car, what upstream causes of catalyst damage should be ruled out?','["A restricted muffler backing exhaust heat up into the catalyst brick", "Heat cycling from normal commuting fatiguing the ceramic substrate", "A lazy thermostat keeping the exhaust stream below catalyst light-off", "Misfires, oil or coolant consumption, and persistent rich running"]'::jsonb,3,'Catalysts rarely die alone; misfire history, oil or coolant entering the exhaust, and rich fueling all poison or overheat the substrate — and will kill a new cat too.' FROM public.challenges WHERE slug='p0420-cat-efficiency' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'Records show a P0303 six months ago that was ''fixed'' by clearing codes. Why does that matter for this diagnosis?','["Sustained misfire dumps raw fuel that overheats and degrades the catalyst", "An old misfire code permanently inflates the catalyst monitor''s failure counters", "Cylinder 3''s exhaust port feeds the front face of this catalyst brick", "It means the rear O2 sensor was probably damaged at the same time"]'::jsonb,0,'Unburned fuel from a misfiring cylinder ignites inside the converter and can melt or glaze the substrate — an uncorrected misfire is a leading catalyst killer.' FROM public.challenges WHERE slug='p0420-cat-efficiency' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',5,'The old P0303 turns out to be a still-lazy injector, confirmed by a drop test. What''s the correct repair scope?','["Replace the catalyst first, then re-evaluate the injector on the retest", "Clean the injector ultrasonically and keep the original catalyst in place", "Fix the injector, then replace the catalyst that its misfires damaged", "Replace the injector and swap the rear O2 to rebaseline the monitor"]'::jsonb,2,'Both faults are real: the injector caused the damage and the catalyst carries it. A new cat without the injector fix would be sacrificed to the same misfire.' FROM public.challenges WHERE slug='p0420-cat-efficiency' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'The customer asks about a $180 universal catalyst versus the $900 OEM unit. What''s the honest technical trade-off?','["Universal units actually flow better but trip the monitor until the ECM adapts", "The only real difference is the flange fitment and the install labor", "Universal cats need the rear sensor spaced back to read correctly", "Budget cats often carry too little washcoat loading to keep passing long-term"]'::jsonb,3,'Low-cost converters frequently use thinner precious-metal washcoats; they can pass at install and fail the efficiency monitor months later on OBD-II-strict platforms.' FROM public.challenges WHERE slug='p0420-cat-efficiency' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'After the injector fix and OEM cat install, what confirms the repair beyond the MIL staying off overnight?','["Rear O2 voltage pinned near a steady 0.45V from the first mile after the install", "The catalyst monitor running to completion with the rear O2 staying damped", "Fuel trims returning to single digits at both idle and steady cruise", "A tailpipe HC reading comfortably below the state inspection cutoff"]'::jsonb,1,'The definitive pass is the ECM''s own catalyst monitor completing with damped rear-sensor activity — the same test that failed the old converter.' FROM public.challenges WHERE slug='p0420-cat-efficiency' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'Three months later the car returns with P0420 pending — but only after long highway trips; city driving never sets it. Freeze frame shows high load at 75 mph. First move?','["Log front and rear O2 on a highway pull to see if damping collapses at load", "Warranty the new OEM converter as an early infant-mortality failure", "Assume a pinhole exhaust leak and start smoke testing at the manifold", "Suspect adaptive fueling leaning things out at cruise and reflash the ECM first"]'::jsonb,0,'A condition-specific monitor failure calls for data captured in that condition; watching both O2 signals during a highway pull shows whether damping genuinely collapses under sustained load.' FROM public.challenges WHERE slug='p0420-cat-efficiency' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'The highway capture shows rear O2 damping collapse only above 70 mph sustained, and a smoke test then finds a hairline crack at the flex-pipe weld ahead of the rear sensor. Why did this fool the monitor only at speed?','["Greater exhaust pressure at speed pushes unconverted exhaust straight past the rear sensor", "Highway heat expands the crack closed and traps oxygen at the sensor tip", "High flow pulls outside air in at the crack, adding oxygen swings at the rear sensor", "The flex pipe''s movement at speed works the sensor connector partially loose"]'::jsonb,2,'A small breach near the rear sensor lets ambient air get drawn in under high flow, and the added oxygen makes the rear signal look active — mimicking a failed catalyst even though the new one is fine.' FROM public.challenges WHERE slug='p0420-cat-efficiency' ON CONFLICT DO NOTHING;

-- u0101-no-comm-tcm
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'Several modules store U0101 and the scan tool can''t reach the TCM, but every other module responds. What does this pattern point to first?','["A failed gateway blocking diagnostic sessions to one address", "A bus-wide termination fault raising the noise floor for all traffic", "A scan tool protocol mismatch with the transmission sub-network", "A problem local to the TCM \u2014 its power, ground, or bus connection"]'::jsonb,3,'When exactly one module drops off and the rest of the bus is healthy, suspicion goes to that module''s own supplies and its branch of the network, not the shared bus.' FROM public.challenges WHERE slug='u0101-no-comm-tcm' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',1,'What should be checked before any wiring diagrams come out?','["The TCM''s fuses and relays in both the engine-bay and cabin boxes", "TSBs covering TCM software lockups that mimic a network failure", "Bus resistance at the data link connector to clear the network side", "Fluid level and condition, in case the internal harness is exposed"]'::jsonb,0,'A no-comm module is a power-supply problem until proven otherwise; fuse and relay checks take two minutes and clear the most common cause before deeper testing.' FROM public.challenges WHERE slug='u0101-no-comm-tcm' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',2,'Fuses are good. At the TCM connector, key on: power pins read 12.5V, grounds drop-test at 0.02V, but CAN-H and CAN-L both sit flat at 2.5V with no activity. What does this say?','["Steady 2.5V on both wires is the classic signature of CAN-H shorted to CAN-L", "The TCM''s internal transceiver failed and is loading the whole bus down", "Power is good and the stub is silent \u2014 check it for an open back to the splice", "Those are normal idle voltages, so the fault has to be TCM software"]'::jsonb,2,'Voltage without data activity on a powered module''s bus stub points to an open between that stub and the main bus — live traffic would show switching, not a flat 2.5V pair.' FROM public.challenges WHERE slug='u0101-no-comm-tcm' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'How do you test the TCM''s bus stub for an open without cutting into insulation?','["Inject 5V at the TCM end and probe for it at the battery junction box", "Ohm each CAN line from the TCM connector back to the DLC pins", "Measure resistance across CAN-H and CAN-L at the DLC one more time", "Backprobe the splice pack and wiggle the harness while watching voltage"]'::jsonb,1,'With the battery disconnected, point-to-point continuity from the module connector to a known bus access point like the DLC proves each stub wire end to end.' FROM public.challenges WHERE slug='u0101-no-comm-tcm' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'CAN-H ohms out fine; CAN-L reads open between the TCM and the splice. That harness section runs along the transmission case. Most likely physical cause on this truck?','["Fretting inside the splice pack from driveline torque reversals", "Heat from the exhaust hardening the insulation until the conductor cracked", "A previous transmission service pinching the loom under the pan rail", "Chafe-through where the harness contacts the case or a clamp edge"]'::jsonb,3,'Harness runs along vibrating cast surfaces fail where they rub; a clamp edge or casting boss chews through insulation and eventually the conductor itself.' FROM public.challenges WHERE slug='u0101-no-comm-tcm' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',5,'The chafed section sits where a missing clip let the loom rest on a bellhousing rib. Correct repair for the opened CAN-L wire?','["Splice with sealed connectors, re-loom, and restore the missing clip", "Use a crimped repair sleeve, fresh loom, and a zip tie straight to the rib", "Solder the conductor, tape the section, and lay the slack off the rib", "Run a new CAN-L jumper outside the loom from the splice to the TCM"]'::jsonb,0,'The repair has to fix the wire and the root cause: a sealed splice restores the circuit, and replacing the lost retainer keeps the harness off the surface that wore it through.' FROM public.challenges WHERE slug='u0101-no-comm-tcm' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'After repair, the TCM communicates and shifts normally. U0101 remains stored in the PCM, ABS, and cluster as history codes. Correct handling?','["Leave the history codes alone; they age out after enough warm-up cycles", "Clear all modules, drive it normally, and rescan to confirm none return", "Clear only the TCM so the other modules keep evidence for the record", "Clear the modules one per day and watch which of them re-sets first"]'::jsonb,1,'History U-codes in other modules are residue of the outage; the closing step is a full clear, a normal drive, then a rescan proving the network stays clean.' FROM public.challenges WHERE slug='u0101-no-comm-tcm' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'What was the giveaway, early on, that this was NOT a bus-wide problem worth resistance-testing first?','["The wrench lamp \u2014 a bus-wide fault would set the red network icon instead", "U0101 by definition can only ever set for wiring opens right at the TCM", "All the other modules stayed reachable while only the TCM dropped off", "The truck still started and drove, which rules out any shared-bus fault"]'::jsonb,2,'A dead shared bus takes many modules down together; one silent module on an otherwise-normal network localizes the fault to that module''s branch from the start.' FROM public.challenges WHERE slug='u0101-no-comm-tcm' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'A fleet manager asks how to keep this failure from recurring across their other trucks. Most useful recommendation?','["Have techs verify harness clips are restored after any transmission work", "Add supplemental loom over every driveline harness at the next service", "Scan every truck monthly so network faults get caught before limp mode hits", "Put the fleet''s harnesses on a scheduled two-year replacement interval"]'::jsonb,0,'The failure traced to a retainer lost during earlier service; making clip restoration an explicit checklist item attacks the actual root cause at fleet scale.' FROM public.challenges WHERE slug='u0101-no-comm-tcm' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'Generalize this case: when a scan tool can''t reach exactly one module, what''s the efficient test order?','["Bus resistance, then module power, then the stub \u2014 cheapest test first", "Reflash the silent module first, since firmware hangs outnumber wiring faults", "Substitute a known-good module before spending time on wiring tests", "Power and grounds at the module, then its bus stub, then the module itself"]'::jsonb,3,'Supplies, then the branch circuit, then the module: each step is cheaper and more likely than the next, and it condemns the module only after its inputs are proven good.' FROM public.challenges WHERE slug='u0101-no-comm-tcm' ON CONFLICT DO NOTHING;

