-- 021_shop_lore_challenges.sql
-- Three narrative 'shop lore' challenges built around misleading cases: the
-- classic hot-soak/'vanilla ice cream' no-start (Fuel), an event-driven wake
-- fault masquerading as a ghost/parasitic draw (Electrical), and a harsh-shift
-- complaint quoted as an overhaul whose root cause is a corroded ground putting
-- the TCM in failsafe (Drivetrain). Authored to the migration-019 distractor
-- standard and validated (positions, length gaps, phrase frequency, throwaways)
-- against the combined live bank before shipping.

INSERT INTO public.challenges (slug,title,type,specialty,xp_reward,description,tags) VALUES
  ('hot-soak-ice-cream-nostart','The Ice Cream Run — Hot-Soak No-Start','component','Automotive',150,'2013 Chevy Impala 3.6L. Runs perfectly all day — unless the owner makes a quick ten-minute stop; then it cranks forever before starting. She insists it only happens when she stops for ice cream. No codes stored.',ARRAY['Fuel System','Hot Soak','Shop Lore']),
  ('haunted-minivan-3am','The Haunted Minivan — Lights at 3 A.M.','wiring','Automotive',150,'2017 Honda Odyssey. Doorbell-camera footage shows the interior lights coming on by themselves at 3 a.m., the power sliding door cycling once, and a dead battery by morning. Weeks can pass between events. The owner is only half-joking about a ghost.',ARRAY['Intermittent','BCM','Battery Drain','Shop Lore']),
  ('ro-3800-second-opinion','Repair Order — The $3,800 Second Opinion','ro','Automotive',160,'2016 Ford Escape 2.0T. Another shop quoted a $3,800 transmission overhaul for harsh, erratic shifting. The customer wants a second opinion first — and mentions in passing that the battery light flickered once last month.',ARRAY['Transmission','Repair Order','Misdiagnosis','Grounds'])
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.challenge_domains (challenge_id,domain) SELECT id,'Fuel'::public.skill_domain FROM public.challenges WHERE slug='hot-soak-ice-cream-nostart' ON CONFLICT DO NOTHING;
INSERT INTO public.challenge_domains (challenge_id,domain) SELECT id,'Electrical'::public.skill_domain FROM public.challenges WHERE slug='haunted-minivan-3am' ON CONFLICT DO NOTHING;
INSERT INTO public.challenge_domains (challenge_id,domain) SELECT id,'Drivetrain'::public.skill_domain FROM public.challenges WHERE slug='ro-3800-second-opinion' ON CONFLICT DO NOTHING;

-- hot-soak-ice-cream-nostart
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'The owner insists the car only fails to start after she stops for ice cream. The pattern sounds absurd — but what real variable is it actually describing?','["Evening ambient temperatures dropping while the car sits parked outside", "Idle-heavy driving on the way to the store gradually fouling the plugs", "A short hot-soak: a brief stop that lets underhood temps peak without cooling", "The electrical load of unlocking and reopening the car while it''s still hot"]'::jsonb,2,'Ten minutes parked is exactly when heat-soaked underhood temperatures peak — the ''ice cream'' detail encodes stop duration, and short stops are the classic hot-soak failure window.' FROM public.challenges WHERE slug='hot-soak-ice-cream-nostart' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',1,'With no codes stored, what data capture sets up the diagnosis on the next hot-soak event?','["Fuel rail pressure at key-off, again after ten minutes, and during the long crank", "The freeze frame from the most recent failed start attempt", "Battery voltage logged overnight to catch a slow drain building up", "Coolant temperature graphed against the gauge to see whether it lags true engine temp"]'::jsonb,0,'The complaint lives in a ten-minute hot-soak window, so the useful capture is rail pressure across exactly that window — and with no code stored, there is no freeze frame to lean on.' FROM public.challenges WHERE slug='hot-soak-ice-cream-nostart' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',2,'Rail pressure: 55 psi at key-off, 8 psi ten minutes later (spec: hold 45+ psi for 20 minutes). During the long crank it slowly rebuilds to 50 psi. What does the bleed-down indicate?','["Normal thermal contraction of the fuel as the rail cools back down", "A weak pump that can''t build adequate pressure once the fuel is hot", "Vapor forming in the hot rail, which reads as lower liquid pressure", "Pressure escaping through a leaking injector or a failed check valve"]'::jsonb,3,'A sealed rail should hold pressure for many minutes. A fast bleed toward zero means fuel is escaping past an injector or the pump''s check valve — and the crank is long because the rail has to re-prime first.' FROM public.challenges WHERE slug='hot-soak-ice-cream-nostart' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'How do you split the bleed-down suspects — injector versus pump-side check valve — without pulling the rail?','["Swap in a new pump module first, since check valves fail more often", "Repeat the hold test with the supply line blocked off and compare the bleed rate", "Crack open a rail fitting during the bleed-down and listen for vacuum at the port", "Compare hot and cold bleed-down rates to separate the two failure modes"]'::jsonb,1,'Blocking the supply line hydraulically removes the pump side from the circuit; one extra hold test then says whether the leak lives at the rail or behind the block.' FROM public.challenges WHERE slug='hot-soak-ice-cream-nostart' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'With the supply line blocked, the rail bleeds down at the same rate as before. What did this prove?','["The leak is on the rail side \u2014 an injector \u2014 rather than the pump''s check valve", "The pump check valve is now confirmed as the escape path", "The test is invalid, since blocking the supply line also blocks the leak path itself", "Both the pump and at least one injector must be leaking at once"]'::jsonb,0,'With the pump side isolated and the bleed unchanged, the fuel has to be escaping downstream of the block — through an injector into a cylinder or the manifold.' FROM public.challenges WHERE slug='hot-soak-ice-cream-nostart' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',5,'Why would a leaking injector cause a LONG crank after short stops, rather than a no-start or rough running all the time?','["The injector''s leak path only opens above normal operating temperature", "Cranking voltage sag keeps the leaking injector from firing until pressure recovers", "During the soak it floods a cylinder and empties the rail; re-primed, it runs clean", "The drip leans the mixture out until the pump finally catches back up"]'::jsonb,2,'A leaking injector does its damage while parked — bleeding the rail down and wetting one cylinder. The restart takes extra cranking to rebuild pressure and clear the flooded cylinder, after which everything looks normal.' FROM public.challenges WHERE slug='hot-soak-ice-cream-nostart' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'An injector leak-down test flags injector #4. The customer, hearing the story, asks whether premium fuel would have prevented this. Best answer?','["Yes \u2014 premium''s stronger detergent package would likely have kept the pintle seat sealing", "No; octane has no bearing on injector sealing \u2014 this is wear or debris at the seat", "Only with ethanol-free premium, which is gentler on injector seals", "Premium would have masked the symptom by vaporizing less inside the hot rail"]'::jsonb,1,'Octane rating is knock resistance and nothing else; injector leakage is a mechanical sealing failure. Detergent levels vary by brand, not by grade, so ''premium prevents it'' doesn''t hold.' FROM public.challenges WHERE slug='hot-soak-ice-cream-nostart' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'Injector #4 replaced; the rail now holds 48 psi after 20 minutes. Given the customer''s ''ice cream'' framing, what proves the fix against the original complaint?','["A cold start the next morning after the full overnight soak", "Three consecutive hot restarts performed in the bay with everything at full temperature", "An extended highway drive running the new injector through every duty cycle", "Reproducing the exact event: full warm-up, a ten-minute stop, then a timed restart"]'::jsonb,3,'Verification means reproducing the failing condition, not a related one. Back-to-back restarts skip the soak interval where this fault lived; the ten-minute stop is the test.' FROM public.challenges WHERE slug='hot-soak-ice-cream-nostart' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'What should the RO say to make this diagnosis auditable, given the odd customer narrative?','["The condition, translated: ''extended crank after 5-15 min hot soak'', plus the pressure data", "The customer''s account quoted verbatim so the story stays in her own words", "No narrative at all \u2014 unusual complaints tend to undermine warranty claims", "''Intermittent long crank, cause found and corrected'' with the replacement part number attached"]'::jsonb,0,'The tech''s job on paper is converting anecdote into a reproducible condition statement backed by measurements — that''s what a warranty auditor or the next tech can actually use.' FROM public.challenges WHERE slug='hot-soak-ice-cream-nostart' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'The famous ''vanilla ice cream'' version of this complaint — fine after chocolate, no-start after vanilla — was real and solved the same way. What''s the general lesson?','["Customers tend to misremember conditions, so odd patterns should be set aside", "Complaints like these are placebo effects that resolve once explained calmly", "Absurd-sounding patterns usually encode a real variable \u2014 find what they measure", "Strange correlations mean intermittent electronics until proven otherwise"]'::jsonb,2,'In the classic case, vanilla was sold from the front counter — a faster stop — so the car failed only on short hot soaks. The correlation was accurate data; the tech''s job was decoding which variable it tracked.' FROM public.challenges WHERE slug='hot-soak-ice-cream-nostart' ON CONFLICT DO NOTHING;

-- haunted-minivan-3am
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'Doorbell-camera footage shows the van''s interior lights coming on at 3 a.m. and the sliding door cycling once. What class of fault does this rule IN immediately?','["Something is waking the body electronics \u2014 an event, not a steady drain", "A failing battery self-discharging internally through the night", "Routine periodic self-tests that this platform runs while parked", "A steady parasitic draw sitting just large enough to trigger the dome lighting"]'::jsonb,0,'Lights turning on and a door cycling are commanded actions — wake events. A steady draw drains silently; something is actively waking the BCM, which changes the entire hunt.' FROM public.challenges WHERE slug='haunted-minivan-3am' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',1,'Why is a standard key-off draw test in the shop likely to come back clean on this van?','["Vans with power sliding doors don''t reach sleep on a lift", "A draw this size only shows up on the AC side of the charging system", "The dead battery from the last event masks the true draw until it gets replaced", "The wake events are intermittent; between them, sleep current is truly normal"]'::jsonb,3,'An event-driven fault passes any spot check taken between events; the van genuinely sleeps at normal current right up until whatever wakes it fires again.' FROM public.challenges WHERE slug='haunted-minivan-3am' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',2,'What''s the right tool strategy for a fault that fires at 3 a.m., sometimes weeks apart?','["Keep the van for a week and pull one fuse per night until the events finally stop", "A current logger on the battery plus the BCM''s wake-reason log running overnight", "Ask the owner to aim the camera at the fuse box for the next event", "Replace the battery and see whether the events survive the swap"]'::jsonb,1,'Sparse intermittents get caught by instrumentation left in place, not by shop visits. Modern BCMs log their wake sources, and a current logger timestamps every event for correlation.' FROM public.challenges WHERE slug='haunted-minivan-3am' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'The BCM wake log shows repeated events sourced to ''driver sliding door latch'', and the camera timestamps line up. What''s the implication?','["The BCM is corrupt and inventing phantom sources for its own internal fault", "The sliding door motor is back-driving voltage into the latch sensing circuit", "A latch switch is chattering, waking the BCM and firing its scripted door logic", "The owner''s phone app is polling the door module remotely during the night"]'::jsonb,2,'A wake log naming one input, corroborated by video timing, is direct evidence: the latch switch is chattering, and every ''ghost'' behavior is the BCM''s normal scripted response to a door event.' FROM public.challenges WHERE slug='haunted-minivan-3am' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'Why would a failing latch microswitch act up mostly in the small hours of the night?','["The BCM raises its input sensitivity while the vehicle is asleep", "System voltage rises slightly at night and retriggers marginal inputs", "Street parking tilts the sliding door just enough overnight to shift the latch mechanism", "Overnight cooling and condensation shift contact resistance in a marginal switch"]'::jsonb,3,'Marginal contacts are temperature- and moisture-sensitive; cool, damp overnight hours are when an almost-failed switch crosses its threshold — which is exactly why afternoon shop checks found nothing.' FROM public.challenges WHERE slug='haunted-minivan-3am' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',5,'How do you confirm the latch switch is the culprit before ordering parts, given it won''t act up on demand?','["Watch the latch input live while cycling the door and chilling or misting the latch", "Unplug the latch connector for a few nights and call it proven if the ghost stays away", "Ohm the switch once at room temperature against the specification", "Swap latches side to side and wait to see whether the fault follows"]'::jsonb,0,'The switch is condition-sensitive, so recreate its conditions: watch the BCM''s live latch state while working the door cold and damp. A flickering input under provocation is proof on demand.' FROM public.challenges WHERE slug='haunted-minivan-3am' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'The latch input flickers when misted. The customer asks why this killed the battery when the lights ''only stayed on a minute''. What''s the actual mechanism?','["Interior LEDs draw several times their rating once they''ve warmed up", "The sliding door motor stalls against its lock and pulls heavy current through the night", "Each wake restarts every module''s sleep timer; dozens of wakes add up to hours awake", "Dome lights cycled nightly are enough on their own to flatten a battery"]'::jsonb,2,'The cost isn''t the lights — it''s that every wake event holds the whole network awake through another sleep-timer countdown. A latch chattering dozens of times a night can keep modules drawing until dawn.' FROM public.challenges WHERE slug='haunted-minivan-3am' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'Latch assembly replaced and the wake log cleared. What''s the verification standard for a fault that fired weeks apart?','["One quiet night parked in the shop lot before handing the van back to the owner", "The owner keeps the van and calls back if the ghost ever returns", "Clear everything and treat a silent weekend as sufficient proof", "An agreed monitoring period with the logger on and zero unexplained wake events"]'::jsonb,3,'For sparse intermittents you can''t verify by casually observing the failure''s absence — you define a monitoring window, instrument it, and release with data rather than hope.' FROM public.challenges WHERE slug='haunted-minivan-3am' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'In hindsight, what was the owner''s half-joking ''ghost'' report actually worth as diagnostic input?','["It was precise telemetry \u2014 timestamps and behaviors that mapped onto the wake log", "It biased the diagnosis from the start and should have been screened out at intake", "It became useful only once the camera replaced her verbal account", "It pointed at the wrong system and cost real diagnostic time"]'::jsonb,0,'The customer supplied timestamped video of the exact failure — better data than most intermittents ever get. Treating odd reports as evidence rather than noise is what cracked the case.' FROM public.challenges WHERE slug='haunted-minivan-3am' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'Generalize: on a logged current trace, what separates an event-driven drain from a classic steady parasitic draw?','["Event drains trace back to door latch and lighting circuits in nearly every real case", "Spikes of wake current with healthy sleep between them, versus one flat elevated line", "Steady draws can''t kill a battery in a single night the way events can", "Event drains don''t show on a bench draw test, while steady ones reliably do"]'::jsonb,1,'An event drain is bursts of wake current separated by normal sleep; a classic draw is a flat line that never reaches sleep spec. The shape of the trace tells you which hunt to run.' FROM public.challenges WHERE slug='haunted-minivan-3am' ON CONFLICT DO NOTHING;

-- ro-3800-second-opinion
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'The intake notes: harsh erratic shifting, a $3,800 overhaul quote from another shop, and the customer''s aside that the battery light ''flickered once last month''. What comes first?','["Adopt the other shop''s findings, since they already had the pan down", "A full code scan and road test before inheriting anyone''s diagnosis", "Chase the battery light remark \u2014 charging faults explain everything here", "Quote the overhaul too; at this mileage the unit is simply due"]'::jsonb,1,'A second opinion starts from zero: reproduce the symptom and scan every module yourself. The other shop''s conclusion and the customer''s asides are leads to test, not verdicts to inherit.' FROM public.challenges WHERE slug='ro-3800-second-opinion' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',1,'The scan returns P0705 (range sensor), P0973 (shift solenoid A circuit), and U0100 — faults across electrically unrelated circuits. What does that spread suggest?','["The valve body is failing and taking its attached sensors down with it", "A TCM with output drivers failing across multiple channels at once", "A shared supply or ground problem upstream of all three circuits", "Ordinary stored-code clutter for a vehicle with this many miles"]'::jsonb,2,'Multiple circuit codes in unrelated circuits rarely mean multiple failures — they point at what those circuits share: power feeds and grounds.' FROM public.challenges WHERE slug='ro-3800-second-opinion' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',2,'On the lift, wiggling the engine-to-body ground strap makes the TCM''s supply-voltage PID dip from 13.8V to 11.2V. What has been established?','["A resistive ground is sagging the TCM''s supply \u2014 the electrical thread is real", "The scan tool''s own DLC connection is faulty and corrupting the voltage PID stream", "Normal engine rock momentarily unloads the alternator''s output", "The TCM''s internal regulator is breaking down under vibration"]'::jsonb,0,'Supply voltage that tracks physical movement of a ground strap is a live demonstration of resistance at that strap — the flickering battery light and the code spread now share a mechanism.' FROM public.challenges WHERE slug='ro-3800-second-opinion' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'Why does a TCM with implausible sensor inputs produce HARSH shifts specifically, rather than no shifts at all?','["Low voltage slows solenoid response, letting clutches slip before locking", "The torque converter stays locked through each shift when voltage sags", "Electrical noise gradually corrupts the shift maps held in TCM memory", "Failsafe strategy commands high line pressure to protect the clutches"]'::jsonb,3,'When inputs go implausible the TCM drops into failsafe: elevated line pressure and simplified shift logic to prevent clutch slip damage. The harshness is a protective strategy, not mechanical failure.' FROM public.challenges WHERE slug='ro-3800-second-opinion' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'The strap''s crimp is green with corrosion and drops 0.9V under cranking load (spec <0.1V). The first shop measured line pressure ''high and surging'' and condemned the pump. What actually happened in their test?','["Their pressure gauge was out of calibration by roughly the same margin", "They measured failsafe''s commanded high pressure and read it as a pump fault", "The pump genuinely is surging; two independent faults coexist here", "The high line pressure simply confirms their sticking-regulator-valve diagnosis"]'::jsonb,1,'In failsafe the TCM commands elevated line pressure on purpose; ''high and erratic'' readings were the strategy responding to bad references. Their data was fine — the interpretation missed the operating mode.' FROM public.challenges WHERE slug='ro-3800-second-opinion' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',5,'Ground strap replaced, terminals cleaned, drop now 0.03V, codes cleared. What must happen BEFORE any verdict on shift quality?','["Re-check line pressure to confirm the pump has finally settled down", "Replace the range sensor anyway, since P0705 was stored against it", "A relearn drive so the TCM exits failsafe and rebuilds its shift adaptives", "An immediate road test \u2014 if it still shifts hard, the first shop was right"]'::jsonb,2,'Right after the repair the TCM still carries failsafe state and stale adaptives; judging shift quality before a relearn drive would falsely condemn a transmission that just got its senses back.' FROM public.challenges WHERE slug='ro-3800-second-opinion' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'After the relearn drive the shifts are smooth, no codes return, and the voltage PIDs stay rock-steady through wiggle tests. How should the second-opinion RO frame the original $3,800 quote?','["State the findings and data: symptoms traced to a ground fault, not internal wear", "Name the other shop''s misdiagnosis explicitly so the customer can pursue a refund", "Soften it \u2014 the transmission was ''starting to fail'' and this repair bought time", "Recommend the overhaul anyway as preventive maintenance at this mileage"]'::jsonb,0,'The RO states what was measured and repaired and lets the data speak, without editorializing about the other shop. Inventing partial vindication would be dishonest in the other direction.' FROM public.challenges WHERE slug='ro-3800-second-opinion' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'What working habit would have saved the first shop from this misdiagnosis?','["Confirming every PID against a second scan tool before trusting it", "Basic electrical checks \u2014 supplies and grounds \u2014 before interpreting transmission data", "Dropping the pan for physical evidence before any electronic diagnosis", "Verifying with a line pressure gauge, which they did \u2014 the data was simply unlucky"]'::jsonb,1,'Every module''s outputs are only as good as its power and ground. Checking supplies first is cheap insurance, because electrical reference faults masquerade as expensive mechanical problems — rarely the reverse.' FROM public.challenges WHERE slug='ro-3800-second-opinion' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'The customer asks: ''So the battery light WAS the clue — why did nobody chase it?'' What''s the honest answer about why such clues get missed?','["Battery lights share no wiring with the TCM, so the link is genuinely obscure", "Shops triage by system, and a charging-system light belongs to a different bay", "It really was unrelated; the ground fault just happened to sit near the alternator", "One-off symptoms read as noise until a mechanism ties them to the main complaint"]'::jsonb,3,'A flickering charge light and harsh shifting share no obvious system, so the clue gets dropped. The discipline that keeps it alive is listing every symptom, however small, and asking what single fault could explain the set.' FROM public.challenges WHERE slug='ro-3800-second-opinion' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'The one-fault-explains-all instinct won this case — but the AWD vibration and slow-crank cases each hid TWO faults. How do professionals hold both ideas at once?','["Assume a single fault under 100k miles and multiple faults beyond it", "Count the symptoms: three or more distinct complaints usually means multiple faults", "Chase the single unifying explanation first, then verify every symptom on its own", "Start from a multiple-fault assumption, since it covers both possibilities"]'::jsonb,2,'Occam''s razor picks the first hypothesis to test, not the final word: pursue the unifying cause, then prove each symptom actually resolved. One fault or several is only knowable in hindsight — verification tells you which you had.' FROM public.challenges WHERE slug='ro-3800-second-opinion' ON CONFLICT DO NOTHING;

