-- 022_five_more_challenges.sql
-- Five challenges rounding out the thin domains: P0087 GDI two-stage fuel (Fuel),
-- P20EE SCR efficiency (Emissions/Diesel), a LIN-bus door-boot chafe (Network),
-- bearing-vs-diff-whine NVH discrimination (Drivetrain), and a P0299 boost leak
-- that defeats static testing (Fuel). Authored to the migration-019 distractor
-- standard; validated against the combined 220-question bank (positions, length
-- gaps, phrase frequency, throwaway patterns) before shipping.

INSERT INTO public.challenges (slug,title,type,specialty,xp_reward,description,tags) VALUES
  ('p0087-gdi-rail-pressure','P0087 — Rail Pressure Low Under Load','dtc','Automotive',130,'2016 Kia Optima 2.0T GDI, 98k miles. Stumbles and sets P0087 on hard acceleration only; smooth everywhere else. A used high-pressure pump was already installed by the owner''s cousin — no change.',ARRAY['GDI','Fuel Pressure','Two-Stage']),
  ('p20ee-scr-efficiency','P20EE — SCR Efficiency Below Threshold','dtc','Diesel',160,'2019 Ram 2500 6.7 Cummins, 88k miles. P20EE with no drivability complaint. Another shop already installed a new outlet NOx sensor and DEF doser; the code was back within two tanks.',ARRAY['SCR','DEF','NOx','Cummins']),
  ('lin-window-radio','The Window That Controls the Radio','wiring','Automotive',140,'2020 VW Jetta. Intermittently the driver''s window stops responding, the mirrors won''t adjust, and the steering-wheel volume buttons go dead — all at once, then everything recovers. U-codes stored against two LIN slave modules.',ARRAY['LIN Bus','Body Electrical','Intermittent']),
  ('diff-whine-vs-bearing','The Hum That Moved to the Other Lane','component','Automotive',130,'2015 Ram 1500 5.7L. A hum at 45-70 mph that the owner swears moves to the other side during lane changes. One shop blamed the rear differential, another the wheel bearings. Nobody has opened anything yet.',ARRAY['Differential','Wheel Bearing','NVH']),
  ('p0299-underboost-tests','P0299 — The Underboost That Passed Every Test','dtc','Automotive',140,'2018 Ford F-150 3.5L EcoBoost. P0299 and hesitation under load, worst with a trailer. Boost checks in the bay pass, a smoke test passed, and the intercooler was already replaced on a hunch.',ARRAY['Turbo','Boost Leak','EcoBoost'])
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.challenge_domains (challenge_id,domain) SELECT id,'Fuel'::public.skill_domain FROM public.challenges WHERE slug='p0087-gdi-rail-pressure' ON CONFLICT DO NOTHING;
INSERT INTO public.challenge_domains (challenge_id,domain) SELECT id,'Emissions'::public.skill_domain FROM public.challenges WHERE slug='p20ee-scr-efficiency' ON CONFLICT DO NOTHING;
INSERT INTO public.challenge_domains (challenge_id,domain) SELECT id,'Network'::public.skill_domain FROM public.challenges WHERE slug='lin-window-radio' ON CONFLICT DO NOTHING;
INSERT INTO public.challenge_domains (challenge_id,domain) SELECT id,'Drivetrain'::public.skill_domain FROM public.challenges WHERE slug='diff-whine-vs-bearing' ON CONFLICT DO NOTHING;
INSERT INTO public.challenge_domains (challenge_id,domain) SELECT id,'Fuel'::public.skill_domain FROM public.challenges WHERE slug='p0299-underboost-tests' ON CONFLICT DO NOTHING;

-- p0087-gdi-rail-pressure
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'GDI fuel systems run two pressure stages. Which pair correctly describes them?','["A low side at 4-6 psi carburetor-style, and a high side near 500 psi at the rail", "A vacuum-referenced low side and a boost-referenced high side trimmed 1:1", "Both sides at 60-90 psi, staged through two in-tank pumps plumbed in series", "An in-tank pump feeding 50-90 psi to a cam-driven pump making 500-3000+ psi"]'::jsonb,3,'GDI splits the work: an electric in-tank pump supplies moderate pressure to a mechanical, cam-driven high-pressure pump that generates the rail''s operating range.' FROM public.challenges WHERE slug='p0087-gdi-rail-pressure' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',1,'P0087 sets only under hard acceleration; the car is smooth otherwise. Why does that load-dependence matter diagnostically?','["It points at ignition breakdown, which also surfaces only under load", "Demand outruns supply only at peak flow, so the weak link is capacity, not control", "It means the rail sensor over-reads once pressure climbs past cruise levels", "It confirms the ECM is knowingly commanding a pressure target it never intends to reach"]'::jsonb,1,'A fault that appears only at maximum demand is a capacity limit somewhere in the supply chain — at light load even a compromised system keeps up.' FROM public.challenges WHERE slug='p0087-gdi-rail-pressure' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',2,'WOT datalog: commanded rail 2900 psi, actual sags to 1400. At the same moment, low-side pressure at the HPFP inlet drops from 65 psi to 12 psi. Where is the fault?','["The low-pressure supply \u2014 the lift pump or its circuit can''t hold flow at demand", "The used HPFP is undersized for this engine and starving the rail all on its own", "The rail pressure sensor is collapsing under vibration at high RPM", "The relief valve inside the HPFP is bleeding off right at peak output"]'::jsonb,0,'The high-pressure pump can''t make pressure from starvation: inlet pressure collapsing at demand puts the fault upstream — which is also why the cousin''s pump swap changed nothing.' FROM public.challenges WHERE slug='p0087-gdi-rail-pressure' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'What are the credible causes of low-side pressure collapse under demand on this car?','["A stuck-open purge valve venting the fuel tank''s operating pressure", "A worn HPFP drive lobe on the intake camshaft rounding off", "A clogging filter or strainer, a tired pump, or sagging control voltage", "Injector seals letting rail pressure bleed back into the low side"]'::jsonb,2,'Low-side capacity is flow through the strainer/filter, the pump''s own health, and the voltage driving it — any of the three sags exactly when demand peaks.' FROM public.challenges WHERE slug='p0087-gdi-rail-pressure' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'The in-tank pump is voltage-controlled by a module. At WOT the module commands 13.2V but only 9.8V arrives at the pump connector. What''s next?','["Replace the control module; it''s failing to deliver what it commands", "Replace the pump; a dragging motor pulls its own feed voltage down exactly like this", "Bypass the module with a relay feed and skip any further diagnosis", "Voltage-drop the feed and ground legs between module and pump to find the loss"]'::jsonb,3,'3.4 volts are being lost somewhere between the module''s output and the pump; drop-testing each leg under load pins the loss to a specific run of wire or connector.' FROM public.challenges WHERE slug='p0087-gdi-rail-pressure' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',5,'The drop test finds 2.9V across the tank-top connector''s feed terminal, and the connector shows heat discoloration. Why do these connectors burn out on high-demand fuel systems?','["Pump current through terminal fretting builds heat, oxide, and yet more resistance", "Ethanol vapor around the tank chemically corrodes the pins from the outside in", "The module''s PWM switching arcs the terminals microscopically on every pulse", "Tank-top heat cycles gradually anneal away the terminal spring tension"]'::jsonb,0,'It''s a feedback loop: a slightly degraded terminal makes heat under current, heat grows oxide, oxide raises resistance, and the connector cooks itself — fastest on circuits that pull hard.' FROM public.challenges WHERE slug='p0087-gdi-rail-pressure' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'Connector pigtail replaced; the low side now holds 58 psi at WOT and the rail tracks commanded pressure. What about the cousin''s used HPFP — leave it or address it?','["Reinstall the original pump, since the used one turned out unnecessary", "Replace it with new; a used high-pressure pump from another engine can''t be trusted", "Verify it: full-range pressure tracking plus a fuel trim check \u2014 if clean, it stays", "Return it under the seller''s parts warranty before the claim window closes"]'::jsonb,2,'The pump''s provenance doesn''t matter; its measurements do. If it tracks commanded pressure across the range and trims are clean, swapping it back out adds labor and risk for nothing.' FROM public.challenges WHERE slug='p0087-gdi-rail-pressure' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'Post-repair trims: LTFT +2% idle, +4% cruise, STFT stable at WOT. The owner asks whether weeks of pressure sag damaged anything. Data-backed answer?','["The catalyst likely overheated from lean running and should be replaced soon", "Trims and pressure tracking look healthy; the data shows no lasting damage", "GDI pumps wear their drive lobes any time rail pressure sags for long", "The injectors will have coked partially closed and need an ultrasonic clean"]'::jsonb,1,'The honest answer comes from the readings: normal trims across ranges and clean pressure tracking are the system reporting itself healthy — no measurement supports selling more work.' FROM public.challenges WHERE slug='p0087-gdi-rail-pressure' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'Beyond not fixing the car, what made the cousin''s used-pump swap a poor diagnostic move?','["It added an unknown variable, giving every later reading two suspects instead of one", "Used fuel components void the emissions warranty on this platform", "The swap wiped out the ECM''s stored fuel pressure history that the diagnosis depended on", "HPFP replacement requires the cam timing to be verified afterward"]'::jsonb,0,'Un-diagnosed parts swaps contaminate the experiment: once an unknown-condition part is in the system, every abnormal reading has to be argued against two components instead of one.' FROM public.challenges WHERE slug='p0087-gdi-rail-pressure' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'Generalize the two-stage lesson: when a high-pressure system underperforms at peak demand, what''s the efficient first split?','["Test the high-pressure side first \u2014 it''s the expensive component, so condemn or clear it early", "Replace both stages together, since they wear as a matched set", "Scope the pump-control PWM signal before taking any pressure readings", "Measure at the boundary between stages: healthy input to the high side clears the low side"]'::jsonb,3,'One reading at the interface between stages halves the search space: if the high-pressure stage is being fed correctly at demand, the problem is downstream; if not, upstream.' FROM public.challenges WHERE slug='p0087-gdi-rail-pressure' ON CONFLICT DO NOTHING;

-- p20ee-scr-efficiency
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'What is a healthy SCR system actually doing?','["Trapping NOx in a zeolite brick that regenerates periodically like a DPF", "Diluting the exhaust stream with DEF vapor to lower measured NOx concentration", "Converting NOx to nitrogen and water over the catalyst using ammonia from DEF", "Cooling the exhaust enough that NOx stops forming downstream of the turbo"]'::jsonb,2,'DEF decomposes to ammonia, and the SCR catalyst uses that ammonia to reduce NOx into nitrogen and water — it''s a chemical conversion, not a trap or a dilution.' FROM public.challenges WHERE slug='p20ee-scr-efficiency' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',1,'P20EE flags low conversion efficiency. Why didn''t the previous shop''s new outlet NOx sensor and doser make it stay fixed?','["Efficiency is computed from inputs those parts didn''t change \u2014 the upstream causes remain", "New NOx sensors need a manual offset relearn that was probably skipped", "Dosers only start metering correctly after an injector-quantity adaptation drive completes", "The code needs three full DEF tanks to age out even after a correct repair"]'::jsonb,0,'The monitor compares inlet and outlet NOx given the dosing it commanded; replacing a sensor and a doser that were both working changes nothing about why conversion is poor.' FROM public.challenges WHERE slug='p20ee-scr-efficiency' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',2,'First data pull at cruise: inlet NOx 450 ppm, outlet 390 ppm, commanded dosing normal, EGTs in range. What does the small delta tell you?','["The outlet NOx sensor is still bad \u2014 390 ppm is the typical failed-high reading", "Inlet NOx is simply too high for any SCR system to keep up with", "The numbers are fine; this calibration''s monitor is just strict", "Reduction is genuinely poor \u2014 little NOx is converting despite normal dosing"]'::jsonb,3,'A healthy SCR converts the large majority of inlet NOx; 450 in and 390 out is around 13% conversion — the inefficiency the monitor flagged is real and measurable.' FROM public.challenges WHERE slug='p20ee-scr-efficiency' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'DEF quality is the cheapest input to rule out. What''s the meaningful test beyond ''it looks clean''?','["Smell it \u2014 a strong ammonia odor means the urea is still active", "Refractometer the concentration; spec is 32.5% urea, and dilution kills conversion", "Check the fill date stamped on the jug against its two-year shelf life", "Send a sample out for laboratory spectroscopy before touching the truck any further"]'::jsonb,1,'A refractometer reads urea concentration in seconds against the 32.5% standard — dilute or degraded DEF starves the catalyst of ammonia no matter what the doser commands.' FROM public.challenges WHERE slug='p20ee-scr-efficiency' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'The refractometer reads 19%. The owner buys DEF in bulk drums for his equipment yard. Likely story and fix?','["The tank heater slowly boiled off the urea over the summer; replace the tank assembly", "The drum DEF was counterfeit \u2014 only pump-dispensed DEF meets the ISO spec", "Water contamination or aged stock diluted it \u2014 drain, flush, refill with fresh spec DEF", "Winter blending; DEF ships diluted in cold months the way washer fluid does"]'::jsonb,2,'Bulk-stored DEF picks up water and degrades with heat and time. The repair is a drain and flush plus a documented refill at spec — then re-measure conversion.' FROM public.challenges WHERE slug='p20ee-scr-efficiency' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',5,'After the refill, conversion improves but the monitor still trips on long grades, where inlet NOx spikes past 900 ppm. Which upstream system deserves the look?','["The VGT \u2014 overboost on grades chills combustion and generates the NOx", "The DPF \u2014 soot slip during regens is poisoning the SCR brick", "Injection timing \u2014 the calibration may be advanced for towing economy", "EGR \u2014 insufficient flow at sustained load lets combustion NOx climb"]'::jsonb,3,'NOx is made in the cylinder, and EGR is the system that suppresses it under load. Commanded-versus-actual EGR flow on a grade pull is the measurable next check.' FROM public.challenges WHERE slug='p20ee-scr-efficiency' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'EGR flow reads 40% below commanded on the grade, and the cooler was ''cleaned'' two years ago per the history. Correct repair scope?','["Command higher DEF dosing to cover the extra NOx and close the RO", "Restore EGR flow \u2014 clean or replace the cooler and valve \u2014 then re-baseline efficiency", "Install a larger doser nozzle to match the truck''s higher NOx output", "Replace the SCR brick itself, since it''s been running inefficient for months on end"]'::jsonb,1,'The SCR is sized for design-intent NOx; masking excess production with more dosing treats the symptom. Fix the NOx source, then measure whether the catalyst recovered.' FROM public.challenges WHERE slug='p20ee-scr-efficiency' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'Why did the first shop''s parts-first approach fail here, in one sentence?','["They replaced the measuring devices instead of asking what the measurements meant", "They installed aftermarket sensors where OEM calibration is mandatory", "They skipped the relearn procedures the new parts required afterward", "They picked the right system to work on but attacked it in the wrong order of operations"]'::jsonb,0,'An efficiency code is a verdict on the whole chemical chain. Swapping the sensor and doser replaced the witnesses; the DEF concentration and EGR flow that actually drove the verdict were never questioned.' FROM public.challenges WHERE slug='p20ee-scr-efficiency' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'The owner asks how to keep his bulk DEF from causing this again. Practical advice?','["Stop buying bulk entirely \u2014 only sealed retail jugs stay in spec long enough to trust", "Add a stabilizer treatment to each drum when it''s first opened", "Store the drums indoors and stir them monthly so the urea can''t settle out", "Keep drums sealed, cool, and rotated by date \u2014 and spot-check with a refractometer"]'::jsonb,3,'DEF keeps well if it''s sealed, kept cool, and used in rotation; heat and open storage degrade it. A $15 refractometer turns ''probably fine'' into a number before it goes in a tank.' FROM public.challenges WHERE slug='p20ee-scr-efficiency' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'Big picture: P20EE names the SCR, but the fixes were DEF quality and EGR flow. What''s the takeaway about efficiency codes?','["Efficiency codes indict a result, not a component \u2014 audit every input before any brick", "Efficiency codes trace to fluid quality at the root in almost every case", "Efficiency monitors are too strict to chase without a TSB in hand", "Efficiency codes mean chemistry is at fault, so hardware replacement is rarely the answer"]'::jsonb,0,'An efficiency monitor grades an outcome produced by many inputs — reagent, dosing, temperatures, upstream NOx, and the catalyst itself. The catalyst is the last suspect cleared, not the first part ordered.' FROM public.challenges WHERE slug='p20ee-scr-efficiency' ON CONFLICT DO NOTHING;

-- lin-window-radio
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'Driver''s window, mirror adjustment, and steering-wheel buttons all fail together, then recover together. What do these systems share on this platform?','["The comfort CAN, which carries every body function in the car", "A LIN bus segment \u2014 one master with several slave nodes on a single wire", "A common fuse feeding all three subsystems from the cabin box", "The infotainment head unit, which gateways every cabin switch input signal"]'::jsonb,1,'Several low-speed cabin devices failing and recovering as a group is the signature of a shared LIN segment — and the U-codes logged against two slave nodes name that segment.' FROM public.challenges WHERE slug='lin-window-radio' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',1,'How does LIN differ from CAN in a way that changes the diagnosis here?','["One master schedules all traffic on a single wire; slaves never speak unprompted", "LIN is just slower CAN, carried on the same two-wire differential pair", "Each LIN node carries its own terminating resistor, exactly as CAN modules all do", "LIN runs at 5V logic levels, which is why scan tools can''t see it"]'::jsonb,0,'LIN is a single-wire, 12V-referenced, master-scheduled bus: no differential pair, no 120-ohm terminators, and nothing happens unless the master polls — which reshapes every test.' FROM public.challenges WHERE slug='lin-window-radio' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',2,'A scope on the LIN line during a failure event shows it sitting flat at 0.4V, instead of idling near 12V with message bursts. What does this state mean?','["Normal sleep \u2014 LIN segments idle low between scheduled frames", "The master has simply stopped scheduling frames, and silence on a LIN line reads as 0V", "The battery feed to the whole segment has dropped out entirely", "Something is clamping the line low \u2014 a shorted slave, chafed wire, or stuck master driver"]'::jsonb,3,'LIN idles high through the master''s pull-up; a silent bus would sit near 12V. A line held at ground means some node or wire fault is physically clamping it.' FROM public.challenges WHERE slug='lin-window-radio' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'Five slaves share the segment. How do you find which node is clamping the line?','["Ohm each node''s LIN pin to ground in circuit and condemn whichever module reads the lowest", "Replace the master module first, since it''s the only node that drives the line", "Unplug slaves one at a time with the scope live; the line releases when the culprit leaves", "Measure supply voltage at each slave and chase whichever one is the outlier"]'::jsonb,2,'Serial disconnection while watching the line catches the fault in the act; in-circuit resistance readings mislead, and this fault is intermittent besides.' FROM public.challenges WHERE slug='lin-window-radio' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'The line releases when the driver''s window module is unplugged. The module is buried in the door. Before ordering one, what''s worth sixty seconds?','["Inspect the door-boot harness \u2014 flexing wires short far more often than modules fail", "Order the module anyway, since on-car module tests are never conclusive", "Re-seat the module connector with dielectric grease and retest for a week", "Swap the window modules between the two doors and watch whether the failure follows the part"]'::jsonb,0,'Unplugging the module also disconnected its wiring stub — and the stub runs through the door boot, the highest-flex, highest-failure stretch of wire in the whole car.' FROM public.challenges WHERE slug='lin-window-radio' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',5,'Inside the boot, two wires show cracked insulation with copper visible — the LIN wire is one of them. What''s the repair standard for wiring in a flexing boot?','["Solder the joints inside the boot under heat-shrink, since solid joints beat any connector", "Fine-strand splices outside the flex zone, sealed, with free slack looped inside the boot", "Tape each exposed conductor individually and re-loom the whole bundle", "Re-route the LIN wire outside the boot along the hinge for strain relief"]'::jsonb,1,'A solder joint inside the flex zone is a stiff spot that cracks again; the repair lives outside the boot on both sides, with flexible wire and free slack doing the bending.' FROM public.challenges WHERE slug='lin-window-radio' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'Why did one chafed wire produce the customer''s strange ''everything at once, then fine'' pattern rather than a single dead window?','["The master reboots each slave in sequence after a fault, causing the wave", "Slaves log the short as a code and self-disable for one key cycle each", "Voltage dips from the window motor stalling were resetting the other nodes on the segment", "Every node shares the one wire, so a clamp silences all of them until the short flexes open"]'::jsonb,3,'On a single-wire bus there''s no partial failure: while the line is clamped, no frame reaches any node, and the moment the chafe flexes open, everything resumes as if nothing happened.' FROM public.challenges WHERE slug='lin-window-radio' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'The U-codes were logged against two slave modules. What would replacing those two modules have accomplished?','["A partial fix \u2014 each new module would have restored its own function", "Nothing \u2014 they were the witnesses reporting the outage, not the cause of it", "A full fix, since freshly installed slaves re-arbitrate the bus at power-up", "It would have shifted the fault to different U-codes and muddied the picture"]'::jsonb,1,'U-codes name nodes that couldn''t be reached or couldn''t hear the bus; on a clamped single-wire segment, that''s everyone. The named modules were victims, same as on CAN — only more so.' FROM public.challenges WHERE slug='lin-window-radio' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'What''s the right post-repair verification for an intermittent flex fault in a door boot?','["One full key cycle with each affected function checked once", "Clear the codes and confirm the steering-wheel volume buttons respond again on a drive", "Scope the LIN line while cycling the door and window through full travel, repeatedly", "Leave a scope hooked up overnight in the lot to catch a recurrence"]'::jsonb,2,'The trigger is motion, not time — overnight logging suits a time-random fault, but a flex fault is verified by working the flex while watching the line stay clean.' FROM public.challenges WHERE slug='lin-window-radio' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'Different failure, same segment: a LIN segment goes fully dead with the line idling high and no frames at all. Where do you look first?','["The master node and its power and ground, since only it can start any traffic", "The longest slave stub, which statistically fails most in service", "The pull-up resistor pack out at the fuse box", "Any slave carrying motor loads, since those are what brown out the whole segment"]'::jsonb,0,'Idle-high silence is the opposite fault from a clamped line: the bus is healthy but nobody is scheduling. On LIN only the master transmits unprompted, so a mute bus points at the master or its supplies.' FROM public.challenges WHERE slug='lin-window-radio' ON CONFLICT DO NOTHING;

-- diff-whine-vs-bearing
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'The owner swears the highway hum ''moves to the other side'' during lane changes. Which component''s noise actually responds to steering input at speed?','["A wheel bearing \u2014 lane changes shift side load onto and off the failing bearing", "The differential \u2014 its spider gears have to speed up whenever the truck changes lanes", "A tire \u2014 lane changes alter the contact patch temperature briefly", "The driveshaft \u2014 U-joint working angles change with body roll"]'::jsonb,0,'Gentle swerves at speed are a bearing load test: the noise growing and fading with side load is the classic tell that separates bearings from everything else in the same speed band.' FROM public.challenges WHERE slug='diff-whine-vs-bearing' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',1,'What''s the complementary throttle test, and what does it separate?','["Rev the engine in neutral at a stop to isolate engine-driven noise", "Brake lightly at highway speed to rule the rotors in or out as a source", "Hold the noise speed on drive, coast, and float \u2014 gear mesh changes, bearings don''t", "Cycle 4WD on and off at highway speed to implicate or fully clear the transfer case"]'::jsonb,2,'Ring-and-pinion whine changes character between drive, coast, and float because tooth contact shifts with load; bearing noise tracks wheel speed and ignores the throttle.' FROM public.challenges WHERE slug='diff-whine-vs-bearing' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',2,'Results: noise identical on drive, coast, and float; louder swerving left, quieter swerving right. Which corner is the suspect?','["The left side \u2014 unloading a bad bearing is what makes it growl", "The right side \u2014 a left swerve loads it; chassis ears settle front versus rear", "The right-side differential carrier bearing living inside the axle center section", "Both rear bearings equally, given the symmetric swerve response"]'::jsonb,1,'Throttle-independence cleared the diff, and the load-sensitive side is the right. A swerve left transfers load to the right side, so the noise rising there points at the right bearing — ears or a temp gun settle front versus rear.' FROM public.challenges WHERE slug='diff-whine-vs-bearing' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'Chassis ears confirm right rear. Before condemning the bearing, what quick physical checks corroborate?','["Pull the differential cover for a gear-pattern check while the truck is in the air", "Measure axle shaft runout with a dial indicator at the flange first", "Re-torque the axle nut to spec and road test it again before anything else", "Wheel play at 12 and 6, roughness by hand, and an IR temp compare after a drive"]'::jsonb,3,'Play, felt roughness, and a hub running hotter than its twin are two-minute confirmations that cost nothing — cheap corroboration before any teardown gets quoted.' FROM public.challenges WHERE slug='diff-whine-vs-bearing' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'The right rear hub runs 30°F hotter than the left, with slight roughness by hand. On this axle the bearing presses onto the shaft. What are the repair implications?','["Press work or a shaft assembly \u2014 and inspect the axle surface for spalling before reuse", "Slide-hammer the old bearing out and press a new one on; the shaft itself never wears", "Run a weld bead inside the old race to shrink it off, then reuse all the hardware", "Replace both rear shafts as a matched pair regardless of their condition"]'::jsonb,0,'A failed pressed bearing frequently scores or spalls its shaft seat; the honest quote includes inspecting the shaft and replacing it if the bearing took the surface with it.' FROM public.challenges WHERE slug='diff-whine-vs-bearing' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',5,'Why did two shops split between ''differential'' and ''wheel bearing'' on this truck without opening anything?','["One of them was hearing the front bearings masking the rear noise", "Diff whine only occurs on trucks with limited-slip, so it was a coin flip", "Both noises live in the same speed band; without load and steer tests they''re twins", "Tire noise on each shop''s particular test route covered the real sound differently"]'::jsonb,2,'A 45-70 mph hum is the shared costume of bearings, gear mesh, and tires. The discriminators are behavioral — throttle response and side load — not the sound itself.' FROM public.challenges WHERE slug='diff-whine-vs-bearing' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'New bearing installed; the 45-60 noise is gone — but the owner now reports a faint whine above 70 that ''wasn''t there before''. First move?','["Warranty the bearing job right away, since the odds favor a defective replacement part", "Call it new-bearing break-in noise and have him recheck in 500 miles", "Rotate the tires and check whether the new noise moves with them first", "Characterize it fresh \u2014 speed, throttle, and steer response \u2014 before assuming any link"]'::jsonb,3,'A new symptom gets the same discipline as the first one. Quieting a loud fault routinely unmasks a second, softer one that was there all along — assumption is the enemy either way.' FROM public.challenges WHERE slug='diff-whine-vs-bearing' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'The 70+ whine is throttle-sensitive: present on drive, gone on coast. What is it most likely, and why wasn''t it heard before?','["The new bearing changing preload as it beds into the hub", "A driveshaft balance issue that only gets excited above 70", "Ring-and-pinion whine, previously buried under the louder bearing roar", "Transmission output-shaft bearing noise carrying down the driveshaft"]'::jsonb,2,'Load-sensitivity is gear mesh''s signature — the exact behavior the first noise lacked. The bearing''s roar simply out-shouted it until the repair dropped the noise floor.' FROM public.challenges WHERE slug='diff-whine-vs-bearing' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'Cover off: the pattern shows heavy toe contact and pinion bearing preload measures under spec. The owner tows a boat all summer. What''s the honest repair conversation?','["The bearing job must have disturbed the differential''s setup, so the shop owns this repair", "A worn diff needing proper setup or overhaul \u2014 a separate fault, quoted on its own merits", "An additive and a recheck; pattern issues tend to correct themselves under load", "Tighten the pinion nut until preload reads correct and re-shim nothing"]'::jsonb,1,'An axle bearing job never touches pinion setup, and cranking the pinion nut on a crush sleeve without rebuilding is a classic way to wreck a diff. Two faults, two honest quotes — towing wear explains both.' FROM public.challenges WHERE slug='diff-whine-vs-bearing' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'Wrap the case: what turned a two-shop stalemate into a clean sequence of two verified repairs?','["Better ears \u2014 seat time eventually beats instrumentation on judgment calls like noise", "Opening the differential first, since that''s where the money was", "Replacing the cheaper suspect first as a de facto diagnostic step", "Load, throttle, and steer characterization letting each noise indict its own component"]'::jsonb,3,'Neither shop lacked skill — they lacked discriminating tests. Behavioral characterization gave each noise a fingerprint, and each fingerprint matched exactly one component.' FROM public.challenges WHERE slug='diff-whine-vs-bearing' ON CONFLICT DO NOTHING;

-- p0299-underboost-tests
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'What two values does P0299 fundamentally compare?','["Wastegate duty cycle against measured turbo shaft speed", "Throttle position against the airflow entering the engine", "Barometric pressure against MAP at key-on, engine off", "Commanded boost against measured charge pressure"]'::jsonb,3,'P0299 is the ECM reporting that the boost it asked for never arrived at the manifold — a gap between commanded and actual charge pressure sustained long enough to flag.' FROM public.challenges WHERE slug='p0299-underboost-tests' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',1,'Why can a truck with a real boost leak pass both a bay boost check and a smoke test?','["Smoke machines pressurize the charge system far above anything the turbo ever produces", "Bay tests reach neither full-load torque nor the engine movement that opens the leak", "EcoBoost wastegates automatically mask leaks below about 15 psi", "A recently replaced intercooler resets the ECM''s leak detection logic"]'::jsonb,1,'A smoke machine puts about 1 psi of static pressure into a system that fails at 18 psi with the drivetrain rocking under torque — the test conditions simply never visit where the fault lives.' FROM public.challenges WHERE slug='p0299-underboost-tests' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',2,'Datalog towing a grade: commanded 16 psi, actual 9, and fuel trims jump +14% only during the event. The customer mentions a faint ''sneeze'' sound. What does the trim shift add?','["The engine is deliberately over-fueling to protect the turbo on grades", "A sticking wastegate is bleeding off boost mechanically without losing any metered airflow", "Metered air is escaping after the MAF \u2014 consistent with a charge-side leak under load", "High-load enrichment always skews trims positive by about this much"]'::jsonb,2,'This is the classic split: a leak dumps air the MAF already counted, so the mixture runs lean and trims climb; a wastegate or control fault loses boost without touching the trims.' FROM public.challenges WHERE slug='p0299-underboost-tests' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'Static smoke already ''passed''. How do you make this leak show itself in the bay?','["Pressurize the charge system to real boost with a regulated tester and rock the engine", "Re-run the smoke machine at its maximum output setting while the engine idles in the bay", "Spray soapy water over the couplers while the engine idles in park", "Datalog MAP while holding high RPM in park with no load"]'::jsonb,0,'A charge-pipe test plug and regulated shop air reproduce real boost pressure, and rocking the engine in gear against the brake reproduces the torque movement — the two conditions the fault needs.' FROM public.challenges WHERE slug='p0299-underboost-tests' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'At 18 psi with the engine rocked in gear, the lower intercooler coupler pops audibly and seeps at its clamp. Why did the earlier intercooler replacement miss this?','["The replacement intercooler shipped with a porous end tank straight from the factory line", "That job disturbed and re-seated the coupler \u2014 good enough to pass static tests, not load", "The original intercooler was fine and the new unit is what leaks now", "Couplers only fail when the intercooler behind them is flow-restricted"]'::jsonb,1,'A parts-hunch job handled the failing joint without fixing it: re-seating the coupler let it hold 1 psi of smoke, while 18 psi plus drivetrain torque still popped it open.' FROM public.challenges WHERE slug='p0299-underboost-tests' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',5,'What''s the correct fix for the coupler joint on a truck that tows?','["Add a second worm clamp over the existing coupler as insurance", "A bead of RTV inside the coupler bore for a guaranteed seal", "Safety-wire the coupler ends the way race teams secure theirs under sustained boost", "A new coupler and OEM-style clamp seated on a clean bead, then re-verified at pressure"]'::jsonb,3,'Couplers seal on geometry: fresh rubber, a clean pipe bead, and the designed clamp. Sealant inside a charge pipe risks being eaten by the engine, and doubled clamps just hide a worn joint.' FROM public.challenges WHERE slug='p0299-underboost-tests' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'Post-repair on the same grade: commanded 16, actual 15.8, trims +3%. The customer asks whether the dealer''s earlier ''no fault found'' was incompetence. Fair answer?','["Their tests were real but never included the load window where this fault lived", "It was; any competent test plan would have caught a leak of this size", "The fault most likely didn''t even exist yet at the time of the dealer''s visit", "Dealer scan tools can''t access the boost PIDs this diagnosis needed"]'::jsonb,0,'A test only rules out faults inside the conditions it covered. The dealer''s checks were honest — they just never brought 16 psi and drivetrain torque together the way a loaded grade does.' FROM public.challenges WHERE slug='p0299-underboost-tests' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'Name the split that the fuel trims handed you for free at the very start of this case.','["Turbo versus engine mechanical \u2014 trims expose compression loss directly", "Fuel supply versus air supply \u2014 positive trims mean the fuel pump itself is falling behind", "Leak versus control fault \u2014 escaping metered air moves trims; wastegate faults don''t", "Pre-turbo versus post-turbo restriction, read from the sign of the trims"]'::jsonb,2,'With boost low in both cases, the trims are the tiebreaker: a leak loses air the MAF already measured and pushes trims lean-positive, while a control-side fault loses boost with trims unmoved.' FROM public.challenges WHERE slug='p0299-underboost-tests' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'The customer''s word for the noise — ''the sneeze'' — turned out to be the coupler popping. Professional takeaway?','["Sound descriptions are far too subjective to be worth recording on a repair order", "Onomatopoeia is data \u2014 a sound the customer can name usually maps to a real event", "The detail was coincidence; couplers like this one seep silently", "It only mattered because this particular customer was mechanically inclined"]'::jsonb,1,'Customers hand over more telemetry than they realize; a nameable sound has a source. ''The sneeze'' was the exact moment the leak opened, timestamped for free.' FROM public.challenges WHERE slug='p0299-underboost-tests' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'Generalize: when a fault ''passes every test'', what''s the disciplined response?','["Escalate to parts replacement, since the testing route has been exhausted", "Map what conditions the tests covered, then build one that reaches the complaint''s", "Wait for the fault to worsen until it can fail one of the standard tests", "Re-run the same battery of tests until the intermittent finally decides to cooperate"]'::jsonb,1,'''Passed every test'' really means ''passed every condition we created''. The discipline is mapping the complaint''s actual operating window and engineering a test that reaches it.' FROM public.challenges WHERE slug='p0299-underboost-tests' ON CONFLICT DO NOTHING;

