-- 023_interaction_fault_challenges.sql
-- Five challenges themed around misdiagnosis and interaction faults: a trailer
-- ground fault corrupting CAN (Network), single-tire AWD driveline binding
-- quoted as a coupler (Drivetrain), an EVAP small leak surviving three gas caps
-- (Emissions), smart-charge/BMS strategy misread as failed alternators
-- (Electrical), and CCV carryover quoted as a turbo (Emissions/Diesel).
-- Authored to the migration-019 distractor standard plus the close-call rules
-- (stem holds the tiebreaker; swap-to-known-good wins where readout is instant).
-- Validated against the combined 270-question bank before shipping.

INSERT INTO public.challenges (slug,title,type,specialty,xp_reward,description,tags) VALUES
  ('trailer-can-chaos','The Trailer That Broke the Truck','wiring','Automotive',150,'2019 Chevy Silverado 2500. ABS and trailer-brake warnings, harsh shifts, and a dozen U-codes — but only ever with the customer''s utility trailer hitched. The truck is flawless solo. An aftermarket brake controller went in last winter.',ARRAY['CAN Bus','Trailer','Grounds','Shop Lore']),
  ('awd-tire-mismatch-bind','The Transfer Case That Wasn''t','component','Automotive',140,'2021 Toyota RAV4 AWD. Binding and shudder in tight parking-lot turns, starting two weeks after a single tire was replaced under road-hazard warranty. A driveline shop has already quoted a rear coupler. No codes stored.',ARRAY['AWD','Tires','Driveline','Misdiagnosis']),
  ('p0456-evap-small-leak','P0456 — The Cap That Kept Getting Blamed','dtc','Automotive',130,'2015 Ford Fusion 2.5L. P0456 has returned three times; three gas caps installed, including an OEM cap at the dealer. The light takes about a week to come back after every clear.',ARRAY['EVAP','Smoke Test','Small Leak']),
  ('smart-charge-bms','The Alternator That Wasn''t Broken','component','Automotive',150,'2018 Ford F-150 5.0L. Two alternators installed in six months for ''low charging voltage'' — the customer watches a plug-in voltmeter read 12.9V while driving. Batteries keep dying young too. It all started right after a parts-store battery replacement.',ARRAY['Smart Charging','BMS','Misdiagnosis']),
  ('ccv-oil-in-boots','The Turbo That Was Sweating Oil','component','Diesel',150,'2016 Chevy Silverado 2500 6.6 Duramax, 140k miles. Oil film found in the intercooler boots during a service; another shop quoted a turbocharger for a ''leaking center seal''. No smoke, no oil consumption complaint, power feels normal.',ARRAY['CCV','Turbo','Duramax','Crankcase'])
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.challenge_domains (challenge_id,domain) SELECT id,'Network'::public.skill_domain FROM public.challenges WHERE slug='trailer-can-chaos' ON CONFLICT DO NOTHING;
INSERT INTO public.challenge_domains (challenge_id,domain) SELECT id,'Drivetrain'::public.skill_domain FROM public.challenges WHERE slug='awd-tire-mismatch-bind' ON CONFLICT DO NOTHING;
INSERT INTO public.challenge_domains (challenge_id,domain) SELECT id,'Emissions'::public.skill_domain FROM public.challenges WHERE slug='p0456-evap-small-leak' ON CONFLICT DO NOTHING;
INSERT INTO public.challenge_domains (challenge_id,domain) SELECT id,'Electrical'::public.skill_domain FROM public.challenges WHERE slug='smart-charge-bms' ON CONFLICT DO NOTHING;
INSERT INTO public.challenge_domains (challenge_id,domain) SELECT id,'Emissions'::public.skill_domain FROM public.challenges WHERE slug='ccv-oil-in-boots' ON CONFLICT DO NOTHING;

-- trailer-can-chaos
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'The truck is flawless solo and faulty only with this one trailer connected. What does that correlation establish before any testing begins?','["The trailer''s axle brakes are overloading the truck''s hydraulic system", "The truck''s CAN bus is marginal, and the trailer''s electrical load exposes it", "The fault rides in with the trailer connection \u2014 wiring, controller, or trailer", "Coincidence \u2014 towing load alone can set U-codes on a truck this heavy"]'::jsonb,2,'A fault that appears and disappears with one attachment localizes to that attachment''s path into the truck. It doesn''t yet say which piece — connector, controller install, or trailer — but it fences the search.' FROM public.challenges WHERE slug='trailer-can-chaos' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',1,'Why would a brake-controller install be able to affect network messages at all?','["Aftermarket controllers tap vehicle circuits, and a bad tap can touch or load CAN wiring", "Brake controllers transmit on CAN by regulation, so any unit can flood the bus with traffic", "They draw enough current on apply to brown out the network''s power supply briefly", "The controller''s gain signal shares a pin with CAN at the trailer plug itself"]'::jsonb,0,'The 7-pin carries power, lights, and brake output — no data. The network exposure comes from the install side: taps and routing inside the cab, where a careless splice lands on or beside data wiring.' FROM public.challenges WHERE slug='trailer-can-chaos' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',2,'With the trailer hitched, the CAN waveform at the DLC shows noise bursts synchronized with the brake-output pulses. What mechanism should top the list?','["The controller''s output transistor arcing internally on every pulse", "Brake current returning through a bad ground and shifting module ground references", "Error frames being normal arbitration while the brake controller talks", "The trailer''s brake magnets kicking voltage spikes back into the truck''s 12V rail"]'::jsonb,1,'CAN levels are measured against ground; when heavy brake current can''t get home through its proper ground wire, it drags module ground references around, and the bus corrupts in rhythm with the current. Magnet kickback is real, but it wouldn''t track a sustained offset the way this does.' FROM public.challenges WHERE slug='trailer-can-chaos' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'How do you confirm a ground-offset problem while the fault is active?','["Ohm the trailer plug''s ground pin to the battery post with everything switched off", "Swap in a known-good brake controller and watch whether the errors stop", "Scope the CAN-H line alone and look for amplitude changes during braking", "Measure between the trailer''s ground pin and battery negative while the brakes apply"]'::jsonb,3,'A bad ground only shows its voltage drop while current flows — volts appearing across a ''ground'' under load is the direct evidence. Static ohms pass marginal grounds all day, and a controller swap tests a different hypothesis than the one on the table.' FROM public.challenges WHERE slug='trailer-can-chaos' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'That measurement reads 2.8V during brake application (spec: near zero). Where is the brake current going instead of the ground wire?','["It stops flowing entirely, which is why the trailer''s brakes feel weak", "Backwards up the brake output wire, effectively doubling the controller''s working load", "Through whatever metal touches \u2014 hitch, ball, chains \u2014 and the truck''s body grounds", "Into the CAN shield drain, which routes it safely to the ECM''s case"]'::jsonb,2,'Current always finds a return. Blocked at the connector, it flows through hitch hardware into the truck body — and every module grounded to that body now sits on a shifting reference.' FROM public.challenges WHERE slug='trailer-can-chaos' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',5,'The 7-pin socket''s ground terminal is green and loose, and the installer scotch-locked the controller''s ground into a dash harness. Correct repair?','["Repair the socket ground and land the controller''s ground on the proper chassis stud", "Add a ground jumper strap from the trailer tongue to the truck bumper", "Upsize the brake output wire so the circuit tolerates the extra resistance", "Clean the green terminal thoroughly, pack it with grease, and re-crimp the scotch-lock tight"]'::jsonb,0,'Both return paths get fixed properly: a sound socket ground for the trailer''s current and a real chassis ground for the controller. Jumper straps and grease are ways of keeping the fault and muffling it.' FROM public.challenges WHERE slug='trailer-can-chaos' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'Grounds repaired; offset now 0.15V under braking, no error frames. Why did the original symptoms include harsh SHIFTING, of all things?','["The TCM cut line pressure to protect itself from the voltage spikes", "Brake pulses were physically jolting the driveline through the hitch", "The trailer''s added mass changes the transmission''s shift scheduling on this platform", "Modules missing bus data fall back to defaults, and the TCM shifts crudely without them"]'::jsonb,3,'The TCM builds shift quality from shared bus data — torque, brake state, grade. When corruption starves it of those messages, it falls back to blunt default tables. Tow/haul scheduling changes shifts too, but it changes them smoothly, not harshly.' FROM public.challenges WHERE slug='trailer-can-chaos' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'The customer asks whether the aftermarket controller is junk and should come out. Evidence-based verdict?','["Yes \u2014 pull the unit from the truck; aftermarket brake controllers cause network faults by design", "The unit tested fine; the installation was the fault \u2014 grounds and routing, now corrected", "Replace it with the OEM integrated controller to remove all doubt", "Keep it, but power it through a relay that drops out whenever the truck is unhitched"]'::jsonb,1,'Separate the device from its installation. With grounds corrected the bus stays clean while the controller operates at full braking — that''s the unit exonerated by data, not by brand loyalty.' FROM public.challenges WHERE slug='trailer-can-chaos' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'Beyond the ground lug, what should a professional install have done differently from the start?','["Proper taps on the right circuits, routed clear of data wiring \u2014 no scotch-locks", "Power drawn from the DLC''s pin 16, which is the sanctioned accessory pickup point", "Twisted-pair extensions on every added wire running through the cab", "A ferrite ring on the brake output line to absorb the apply pulses"]'::jsonb,0,'Install quality is circuit choice plus routing: real crimps or solder on circuits meant to carry the load, kept physically away from data pairs. DLC taps and cargo-cult shielding address problems a clean install never has.' FROM public.challenges WHERE slug='trailer-can-chaos' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'Generalize: a vehicle that''s healthy solo but faulty with an accessory attached — trailer, plow, liftgate. What''s the disciplined framing?','["Condemn the accessory and require an OEM equivalent before further diagnosis", "Treat the truck and the accessory as separate systems and test each on its own", "Test the combined system under working load \u2014 the fault lives in the connection", "Log the vehicle solo for a full week to establish a clean baseline first"]'::jsonb,2,'Each half alone already passes — the complaint says so. Interaction faults live in shared grounds, current paths, and connectors that only exist when the two are mated and working, so that''s the configuration you test.' FROM public.challenges WHERE slug='trailer-can-chaos' ON CONFLICT DO NOTHING;

-- awd-tire-mismatch-bind
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'An AWD vehicle binds and shudders in tight parking-lot turns but drives clean on the highway. What is the driveline fighting in a tight turn that it isn''t fighting straight ahead?','["The higher torque multiplication that low-speed maneuvering demands of the driveline", "Every wheel tracing a different arc, so all four must spin at different speeds", "The inside tire unloading and slipping against the pavement", "Steering geometry dragging the front axle against the rear"]'::jsonb,1,'In a tight turn each wheel follows its own radius, and the differentials and coupler exist to absorb those speed differences. Binding there means something is refusing to let the speeds differ.' FROM public.challenges WHERE slug='awd-tire-mismatch-bind' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',1,'The complaint started two weeks after ONE tire was replaced under road-hazard warranty. Why does a single new tire matter on AWD?','["Fresh rubber grips harder, and the traction system misreads the mismatch", "A new tire runs cooler, shifting its pressure relative to the worn three", "Road-hazard replacement tires use a softer warranty compound that flexes differently", "Its larger circumference turns that wheel slower, loading the driveline constantly"]'::jsonb,3,'Tread depth is circumference: a full-tread tire beside three half-worn ones spins measurably slower every foot of travel, so the coupler absorbs a speed difference that never stops — even driving straight.' FROM public.challenges WHERE slug='awd-tire-mismatch-bind' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',2,'How do you turn ''the tires might be mismatched'' into a number?','["Measure tread depth on all four against the AWD spec, often just a few 32nds", "Check inflation pressures cold, since pressure is what sets effective diameter", "Read the DOT date codes to quantify the age spread across the set", "Weigh each tire \u2014 mass difference tracks wear difference closely"]'::jsonb,0,'Most AWD makers publish a maximum allowable tread or circumference difference across the four corners. A depth gauge turns the hunch into a pass/fail against that spec; pressure matters, but it isn''t the spec.' FROM public.challenges WHERE slug='awd-tire-mismatch-bind' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'Tread reads: new tire 10/32", the other three 4-5/32". The customer asks why the driveline shop''s coupler diagnosis ''felt right'' to them. What did the coupler actually experience?','["Nothing \u2014 the coupler only engages off-road on this model", "Random slip cycles from the traction-control system hunting torque between the axles", "Real heat and wind-up from a nonstop speed difference \u2014 real symptom, wrong source", "Normal operation; the binding feel was purely the new tire''s tread squirm"]'::jsonb,2,'The shop wasn''t hallucinating — the coupler genuinely was hot, worked, and complaining. Diagnosing the component that''s screaming instead of the thing making it scream is the actual mistake.' FROM public.challenges WHERE slug='awd-tire-mismatch-bind' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'Given the other three tires at 4-5/32", what''s the defensible menu for the tire itself?','["Shave the new tire to match, or swap it for one matched to the worn set", "Move the new tire to the front axle, where circumference matters less", "Run the new tire a few PSI low to shrink its circumference into range", "Leave it \u2014 couplers are designed to absorb this much difference long-term"]'::jsonb,0,'Matching circumference is the fix, and shaving or a matched used tire are the two ways there. Pressure tricks overheat the sidewall without changing tread arc much, and axle position doesn''t excuse the mismatch on this driveline.' FROM public.challenges WHERE slug='awd-tire-mismatch-bind' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',5,'The customer has never heard of ''tire shaving'' and suspects an upsell. What''s the fair explanation?','["It''s mostly cosmetic \u2014 matching depths just evens out future wear", "It''s a racing-only service that street shops offer to look premium", "It technically voids the tire''s road-hazard warranty, so replacement is the only real option", "A machine cut matching circumference to the set \u2014 cheaper than a tire, standard for AWD"]'::jsonb,3,'Shaving is an established service exactly for this situation: one damaged tire on an AWD set. Buying tread you immediately remove sounds odd until it''s weighed against a coupler quote.' FROM public.challenges WHERE slug='awd-tire-mismatch-bind' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'Tire shaved to 5/32". How do you verify the driveline actually survived weeks of wind-up, beyond noticing the binding is gone?','["It can''t be verified without opening the coupler for inspection", "Tight circles both ways after a warm drive, plus coupler temperature and fluid checks", "A four-wheel alignment to confirm the geometry baseline", "Clear the AWD control module''s stored adaptives so it relearns the corrected tire sizes"]'::jsonb,1,'Survival is checked functionally and thermally: full-lock maneuvers hot, an IR gun on the coupler against its twin components, and the fluid''s color and smell. The fluid is the flight recorder here.' FROM public.challenges WHERE slug='awd-tire-mismatch-bind' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'The coupler fluid drains dark with a burnt smell. What''s the honest position on the other shop''s $2,400 coupler quote now?','["Still wrong \u2014 the tire was the fault, so the coupler must be fine", "Right all along \u2014 the tire mismatch was incidental to a coupler that was already failing", "It may yet be needed \u2014 the mismatch likely damaged it; service fluid, retest, then decide", "Split the difference and replace only the coupler''s clutch pack"]'::jsonb,2,'Causes create casualties: the tire event was the fault, and the coupler may still be a victim. Burnt fluid says it suffered; whether it survived gets decided by a retest after service, not by either side''s pride.' FROM public.challenges WHERE slug='awd-tire-mismatch-bind' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'After the fluid service and 500 miles, no binding and normal coupler temps. What should the RO capture about the road-hazard tire event?','["Only the shave depth, since that''s the billable operation performed", "A standing recommendation to replace all four tires at the coming rotation visit", "Nothing tire-related \u2014 the driveline service stands on its own record", "The measured depths, the violated spec, and the single-tire trigger for the file"]'::jsonb,3,'The RO is how the next reader inherits the diagnosis. One-tire replacements on AWD are repeat offenders, and a documented pattern stops the next visit from starting at ''transfer case'' again.' FROM public.challenges WHERE slug='awd-tire-mismatch-bind' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'For service writers: what intake question should be standard when any AWD vehicle arrives with a driveline complaint?','["''Any tires replaced recently?'' \u2014 a one-tire event is a leading driveline suspect", "''Do you take it off-road?'' \u2014 abuse history frames the whole diagnosis", "''When was the last alignment done?'' \u2014 geometry drives most binding complaints in practice", "''What brand are the tires?'' \u2014 mixed brands are what the specs prohibit"]'::jsonb,0,'The tire question catches this entire fault class at the counter for free. Brand mixing only matters through circumference, and the spec is a measurement, not a logo.' FROM public.challenges WHERE slug='awd-tire-mismatch-bind' ON CONFLICT DO NOTHING;

-- p0456-evap-small-leak
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'Three gas caps installed — including an OEM cap at the dealer — and P0456 keeps returning. What does that repetition by itself say about the cap hypothesis?','["Nothing certain \u2014 gas caps vary by batch, and the fourth might be the good one", "The cap''s seat on the filler neck must be what''s damaged instead", "It proves the leak is intermittent and driven by weather", "Three tries without an outcome change effectively clears the cap as the cause"]'::jsonb,3,'A part swapped three times — once with a known-good OEM unit — with zero effect on the outcome is a falsified hypothesis. The filler neck is a fair new suspect, but it''s a new hypothesis that needs its own test, not cap number four.' FROM public.challenges WHERE slug='p0456-evap-small-leak' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',1,'Why does the light take about a week to return after each clear, rather than coming right back?','["The leak seals itself until enough vibration reopens it", "The monitor only runs under narrow conditions, so days can pass between attempts", "Small-leak codes need two consecutive failed key cycles before the light commands on", "A cleared code suppresses the EVAP monitor for 100 miles by design"]'::jsonb,1,'The monitor only runs inside a narrow window — roughly mid-tank fuel, the right cold-start delta, a steady drive — so days can pass between attempts. Two-trip logic is real, but it explains two drives, not a week.' FROM public.challenges WHERE slug='p0456-evap-small-leak' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',2,'Smoke machine on the service port, system sealed: the flow gauge shows a small steady flow that never reaches zero, but no smoke is visible anywhere. Next move?','["Condemn the purge valve first, the usual small-leak source on this platform", "Raise the smoke pressure until the leak becomes visible somewhere", "Pinch off branches one at a time and let the flow gauge localize the leak", "Add UV dye to the fuel tank and re-inspect after a week of driving"]'::jsonb,2,'On a true small leak the smoke often never shows; the flow gauge is the real instrument. Sectioning the system splits the search in half per pinch — and turning up the pressure creates leaks in a system rated for inches of water.' FROM public.challenges WHERE slug='p0456-evap-small-leak' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'Flow drops to zero when the purge branch is pinched. Does that condemn the purge valve?','["Not yet \u2014 valve, fitting, or line are all in that branch; vacuum-test the valve next", "Yes \u2014 flow stopping at the valve''s branch is the definition of a failed valve", "No \u2014 pinching any branch drops the flow; the test only proves the machine works", "Yes, and the code history seals it \u2014 purge valves are the known pattern on this model"]'::jsonb,0,'The pinch localized a branch, not a component: everything downstream of that pinch is still in play. A healthy branch wouldn''t have zeroed the flow, so the reading is meaningful — it''s just not yet specific.' FROM public.challenges WHERE slug='p0456-evap-small-leak' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'A hand vacuum pump on the de-energized purge valve holds 20 inHg for five minutes — the valve seals. What''s left in that branch?','["Nothing remains \u2014 retest the whole system; the earlier reading must have been noise", "The valve''s electrical side, since a leaky coil passes vapor once hot", "The charcoal canister, upstream of where the branch was pinched", "The line and fittings between the pinch and the valve \u2014 smoke just that stretch"]'::jsonb,3,'A branch is a valve plus the plumbing that reaches it. With the valve holding vacuum, the remaining suspects are the tubing and connectors in that run — the canister sits on the wrong side of the pinch to explain the reading.' FROM public.challenges WHERE slug='p0456-evap-small-leak' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',5,'The purge line''s quick-connect at the intake has a cracked retainer and a hardened O-ring, and seeps smoke when flexed by hand. Why did it hide from every earlier full-system smoke test?','["Quick-connects only leak with the engine running, which smoke tests skip", "Smoke rises, and this joint sits above the test port''s effective reach", "It seals at rest and opens with movement or heat \u2014 conditions a static test never visits", "Earlier tests used nitrogen, which escapes more slowly than smoke molecule for molecule"]'::jsonb,2,'A hardened O-ring in a cracked retainer is position-dependent: parked and cold it seats, flexed or heat-soaked it gapes. Static tests kept testing the sealed position — the same conditions lesson as every intermittent.' FROM public.challenges WHERE slug='p0456-evap-small-leak' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'What''s the right repair for that quick-connect on an eight-year-old plastic EVAP line?','["A new connector or line section with fresh O-rings; no sealant, no clamps", "Fuel-rated hose slid over both cut ends, secured with EFI-style fuel clamps", "Thread sealant worked into the O-ring boss before re-clipping it", "Epoxy over the cracked retainer, since the O-ring does the actual sealing"]'::jsonb,0,'EVAP joints are engineered seals tested in fractions of a PSI. Hose-and-clamp or sealant bodges pass on the day and reopen with the first big temperature swing — which is exactly the failure being repaired.' FROM public.challenges WHERE slug='p0456-evap-small-leak' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'How do you prove this repair beats the one-week return pattern without keeping the car for a week?','["You can''t \u2014 schedule a recheck and let the warning light be the verdict", "Run the EVAP monitor with the scan tool''s drive-cycle procedure and confirm a pass", "An overnight smoke-machine soak with the flow gauge logging through the entire night", "Clear the codes and perform three cold starts back to back"]'::jsonb,1,'The accuser here is the monitor, so make it testify: meet its enable criteria deliberately and watch it complete and pass. A smoke soak checks the plumbing but never runs the actual judge.' FROM public.challenges WHERE slug='p0456-evap-small-leak' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'Monitor passes and the light stays out. What made the three-cap phase so seductive — and what breaks that trap in general?','["Caps fail often enough that playing those odds three times was rational", "Nothing was wrong with it \u2014 cheap first steps are the mark of disciplined diagnosis", "Swaps felt like progress while measuring nothing; each failure must move the hypothesis", "The dealer''s OEM cap made the theory look validated by authority"]'::jsonb,2,'A cheap first step is fine — once. Repeating it after it failed is motion without information. The discipline is treating every failed fix as data that must move the hypothesis somewhere new.' FROM public.challenges WHERE slug='p0456-evap-small-leak' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'P0455 (gross leak) versus P0456 (small leak): why does the size grading matter for where you look first?','["It doesn''t \u2014 both codes share one leak table and one suspect list", "Gross leaks trace to caps and small leaks trace to lines, almost by definition", "Small-leak codes false-alarm far more often, so P0456 diagnosis starts at the pressure sensor", "Gross means open orifices \u2014 loose cap, fallen hose; small means seals, O-rings, pinholes"]'::jsonb,3,'The monitor sizes the orifice it detects, and orifice size maps to physical fault classes: big openings versus degraded seals. Two different suspect lists, two different first moves — the grading is free triage.' FROM public.challenges WHERE slug='p0456-evap-small-leak' ON CONFLICT DO NOTHING;

-- smart-charge-bms
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'The customer''s plug-in voltmeter shows 12.9V cruising and 14.6V at other times. On a smart-charge vehicle, what is that pattern by itself?','["Potentially normal \u2014 the ECM varies charge voltage for economy and battery state", "A classic failing regulator; a healthy system holds a steady 14.2V at all times", "A ripple symptom \u2014 the average reading droops whenever a diode is down", "Undersized replacement alternators; two duds in a row from one supplier"]'::jsonb,0,'Variable charging commands anywhere from roughly 12.5 to 15V by strategy. The steady-14.2V rule was true of fixed regulators — on this architecture, that veteran rule is exactly the trap.' FROM public.challenges WHERE slug='smart-charge-bms' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',1,'What component tells the ECM how to charge on this truck, and where does it live?','["The instrument cluster''s voltage-sense line at the interior fuse box", "A hall-effect sensor built into the alternator''s rear cover", "The battery monitoring sensor clamped on the negative battery terminal", "A current shunt cast into the underhood fuse box''s main feed"]'::jsonb,2,'The BMS on the negative post measures current in and out, temperature, and state of charge — the charging strategy is built on what this one sensor reports.' FROM public.challenges WHERE slug='smart-charge-bms' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',2,'The complaint history starts right after a parts-store battery replacement. What step does a BMS-equipped vehicle need at battery replacement that often gets skipped?','["A hard ECM reset with both battery cables held together for thirty seconds", "Matching the new battery''s brand to the BMS calibration family", "Re-torquing the negative battery clamp to spec so the sensor reads current accurately", "A battery-state reset, so the system stops managing the old battery''s aged profile"]'::jsonb,3,'The BMS carries a running model of the battery''s age and condition. Without a reset (registration), the strategy keeps treating the fresh battery like the tired one it replaced.' FROM public.challenges WHERE slug='smart-charge-bms' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'How does an unregistered new battery produce the ''batteries keep dying young'' half of this complaint?','["The BMS overcharges the new battery to compensate, slowly boiling off electrolyte over months", "The old profile stays active, chronically undercharging the new battery until it sulfates", "Parasitic-draw protection stays disabled until a registration is performed", "The strategy load-tests the battery on every single start, wearing it down early"]'::jsonb,1,'A strategy tuned for an aged battery holds lower charge targets; the new battery lives perpetually below full charge, sulfates, and dies young — restarting the whole cycle, including the next ''low voltage'' complaint.' FROM public.challenges WHERE slug='smart-charge-bms' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'What measurement separates ''smart charging behaving normally'' from ''genuinely undercharging''?','["Compare the ECM''s commanded charge voltage against measured alternator output", "Overnight resting voltage \u2014 anything above 12.6V proves the charging is adequate", "Headlight brightness compared between idle and 2000 RPM", "A full-field output test measured against the amperage stamped on the case"]'::jsonb,0,'If actual tracks commanded, the hardware is obeying orders, and the investigation moves to why the orders are low — which is data, not parts. A full-field test proves the alternator''s muscle but says nothing about whether the strategy is asking correctly.' FROM public.challenges WHERE slug='smart-charge-bms' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',5,'Scan data: commanded 12.9V, actual 12.9V, and the BMS reports 55% state of charge on a battery that load-tests strong. What''s the verdict on the two replaced alternators?','["The second one fixed part of it and the first was truly bad \u2014 coincidences happen", "Both marginal \u2014 commanding low voltage is how the ECM protects a weak alternator", "Both obeyed their commands faithfully; the money went to the working components", "Unprovable either way without bench-testing the original units"]'::jsonb,2,'Actual matching commanded — twice, across two different units — is the hardware demonstrating innocence. The stuck 55% state-of-charge reading is where the actual fault has been hiding the whole time.' FROM public.challenges WHERE slug='smart-charge-bms' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'You perform the battery registration reset. What should change in the data, and on what timescale?','["Nothing immediate \u2014 the revised strategy phases in over a 500-mile relearn cycle", "Commanded voltage climbs to a proper profile within a drive as SOC re-baselines", "Actual voltage locks to a flat 14.2V, confirming that the reset took", "The BMS reports 100% state of charge immediately and holds there"]'::jsonb,1,'The command responds quickly once the system trusts the battery''s real state. A flat 14.2V would itself be suspicious — variable charging keeps varying by design, which is the same misreading that started this saga.' FROM public.challenges WHERE slug='smart-charge-bms' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'The customer wants to keep his dash voltmeter habit. What''s the honest guidance for reading voltage on a smart-charge truck?','["Below 13V at cruise still means a fault worth a shop visit, every time", "Unplug the BMS connector \u2014 the truck falls back to steady charging and the readings calm down", "Voltmeters are useless on modern trucks; only scan data means anything now", "Watch patterns, not moments \u2014 swings are the design; hard starts signal trouble"]'::jsonb,3,'The meter isn''t wrong, the old interpretation is. Swings are strategy; the meaningful symptoms are cranking behavior and battery life. Unplugging the BMS does force a fallback — along with a code and dumber charging.' FROM public.challenges WHERE slug='smart-charge-bms' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'In the shop''s honest accounting, who should eat the cost of the two alternators?','["The parts store that skipped the registration owns the whole chain of events", "The shop that condemned them \u2014 neither install compared commanded to actual voltage", "The customer, whose voltmeter anxiety drove the repair decisions", "The manufacturer, whose charging strategy reads as a fault to any reasonable technician"]'::jsonb,1,'The parts store started the dominoes, but the discriminating test — commanded versus actual — existed at every visit and was never run. Professional accountability follows the diagnosis, not the trigger.' FROM public.challenges WHERE slug='smart-charge-bms' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'Generalize: what does this case say about applying veteran rules of thumb to newer systems?','["Rules encode assumptions \u2014 when architecture changes, verify the assumption first", "Old rules stay valid, because manufacturers remain obliged to design inside their bounds", "Experience misleads more than it helps on modern vehicles", "A rule of thumb needs a service-manual citation before it''s usable"]'::jsonb,0,'''Healthy systems hold 14.2V'' silently assumed a fixed regulator. The rule''s logic was fine; its assumption expired. The habit that scales is asking what a rule assumes before letting it condemn parts.' FROM public.challenges WHERE slug='smart-charge-bms' ON CONFLICT DO NOTHING;

-- ccv-oil-in-boots
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'Oil film inside the charge pipes of a 140k-mile diesel. Before ''turbo seal'', what''s the boring explanation that has to be ruled out first?','["Fuel dilution migrating up through the intake valves over time", "An overfilled crankcase pushing oil up the dipstick tube and into the airbox", "Normal crankcase carryover \u2014 the CCV system feeds oily vapor into the intake", "Residue left behind by an intake-cleaning additive at a prior service"]'::jsonb,2,'Closed crankcase ventilation feeds oily vapor into the intake on purpose, and a light film is the normal signature at this mileage. Overfill is a real subplot worth a dipstick glance, but carryover is the baseline story.' FROM public.challenges WHERE slug='ccv-oil-in-boots' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',1,'What single observation IN THE INTAKE TRACT would genuinely implicate the turbo''s center-section seals instead?','["Any trace of oil found ahead of the compressor wheel", "Pooling that begins at the compressor outlet while the inlet side stays dry", "Blue smoke on cold start that clears as the engine warms", "Shaft side-play felt at the compressor nut with the inlet ducting removed"]'::jsonb,1,'A seal leak originates at the compressor, so its oil trail starts at the outlet and grows downstream. Shaft play is a fine turbo-health check, but the question is what the intake''s oil distribution can prove — and a dry inlet with a wet outlet is that proof.' FROM public.challenges WHERE slug='ccv-oil-in-boots' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',2,'The inlet duct AHEAD of the compressor turns out just as oily as the boots after it. What does that distribution say?','["The turbo is leaking at both ends, which seals the diagnosis", "Oil migrates backward through the tract at shutdown, so distribution proves nothing", "An oiled-type air filter could be shedding onto the duct", "The oil arrives with the incoming air \u2014 pointing upstream at the CCV, not the turbo"]'::jsonb,3,'The compressor can''t push its own oil upstream against the airflow. Film on both sides means the air arrives pre-oiled — from the CCV inlet (or an over-oiled aftermarket filter, the other upstream source worth a glance).' FROM public.challenges WHERE slug='ccv-oil-in-boots' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'How do you turn ''CCV carryover'' from a story into a measurement on this engine?','["Measure crankcase pressure at the dipstick tube, idle and loaded RPM, against spec", "Weigh the used CCV filter element against a new one''s listed weight for restriction", "Crack the oil cap at idle and judge the vacuum pull by feel", "Vacuum-gauge the intake tract at the boot joint while under boost"]'::jsonb,0,'Crankcase pressure is the system''s report card, and it has a published spec. The oil-cap feel test is a real shop shortcut, but it grades pass/fail by calibrated palm — the gauge produces a number you can defend on an estimate.' FROM public.challenges WHERE slug='ccv-oil-in-boots' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'Crankcase pressure reads three times spec at loaded RPM. What are the two credible causes, and what splits them?','["Turbo seal versus valve seals \u2014 an intake borescope splits them", "A plugged CCV filter versus ring blowby \u2014 a new filter or a blowby check splits them", "Overfill versus oil aeration \u2014 a dipstick reading splits them", "Injector wash-down versus EGR soot loading \u2014 an engine oil lab sample splits the two"]'::jsonb,1,'High crankcase pressure is either flow blocked (the filter — a maintenance part) or flow excessive (blowby from the rings). The filter is cheap with an instant readout on the gauge, so swapping it IS the test here; if pressure stays high, blowby gets measured next.' FROM public.challenges WHERE slug='ccv-oil-in-boots' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',5,'A new CCV filter drops crankcase pressure to spec at every RPM. The service schedule says 45k miles; this one had over 90k on it. Verdict on the $3,000 turbo quote?','["Still plausible \u2014 months of high pressure may have damaged the center-section seals meanwhile", "Justified at the time, given the oil that was found in the boots", "Unsupported \u2014 distribution, pressure data, and the fix all indict the neglected filter", "Right idea, wrong part number \u2014 the quote should have read CCV assembly"]'::jsonb,2,'The evidence chain closes without the turbo ever entering it: oil arrived with the intake air, pressure was high, an overdue service part fixed the pressure. Sustained pressure can stress a turbo''s drain — which is why the retest matters — but suspicion isn''t evidence.' FROM public.challenges WHERE slug='ccv-oil-in-boots' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'How much oil film in charge piping is ''normal'' on a healthy high-mileage diesel — and how does a pro frame that for a worried owner?','["None \u2014 visible oil of any amount means a failed component somewhere", "It varies too much between engines to say; only an oil-consumption test settles it", "Whatever the OEM''s wet-film thickness chart allows per inch of pipe", "A light film is normal carryover; pooling, or growth between services, earns a look"]'::jsonb,3,'The honest line is film-versus-pooling with a time trend. ''Any oil means failure'' condemns every healthy high-mileage diesel on the road, and no wet-film chart exists — precision that specific is a tell for invented spec.' FROM public.challenges WHERE slug='ccv-oil-in-boots' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'The owner asks why the other shop went straight to a $3,000 turbo. What''s the charitable, professional read?','["Oil near a turbo pattern-matches to seals, and pattern was all they had without data", "They likely knew better and simply quoted the more profitable repair", "Their smoke machine couldn''t test crankcase systems, so they defaulted to a parts quote", "These turbos fail often enough that the odds genuinely favored their quote"]'::jsonb,0,'The charitable read is also the instructive one: their pattern recognition was reasonable and their measurement was absent. Pattern minus data is a guess wearing a diagnosis''s clothes — same lesson, kinder framing.' FROM public.challenges WHERE slug='ccv-oil-in-boots' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'What belongs on this RO to keep the NEXT tech from re-quoting the turbo at the next oil-film sighting?','["''Turbo inspected, OK at this time'' along with the current mileage", "The new filter''s part number and its next change-due mileage, kept deliberately simple", "The pressure readings, the overdue filter finding, and that a light film is expected", "A standing recommendation to recheck engine compression at every service"]'::jsonb,2,'The film will be back — normally. The RO that survives is the one carrying the numbers and the expectation forward, so the next set of eyes inherits the diagnosis instead of restarting at the most expensive suspect.' FROM public.challenges WHERE slug='ccv-oil-in-boots' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'Generalize: ''oil where air should be'' on any turbocharged engine. What triage order keeps $3,000 parts on the shelf?','["Compression test first \u2014 the rings sit upstream of everything else", "Map the film''s origin, service-check the vent system, measure pressure \u2014 turbo last", "Borescope the turbo first, since it''s the costliest suspect to get wrong", "Oil analysis first \u2014 wear metals can name the culprit without any disassembly at all"]'::jsonb,1,'Cheapest, most common, most measurable first: the oil''s starting point, the vent system''s service state, then the pressure number. The expensive suspect has to survive every cheap test before it''s allowed on the estimate.' FROM public.challenges WHERE slug='ccv-oil-in-boots' ON CONFLICT DO NOTHING;

