-- 024_reviewed_batch_challenges.sql
-- Three challenges authored under the review gate and approved after expert
-- review (Rev 2): a J1939 backbone fault on a Class 8 truck (Network/Diesel),
-- a serial clutch failure traced to a reused dual-mass flywheel (Drivetrain),
-- and an LML Duramax first-start long crank from suction-side air (Fuel/Diesel).
-- Rev 2 fixes: trailer weight corrected to the G56 2500's rating, platform
-- swapped from 6.7 Powerstroke to LML Duramax for fuel-system accuracy, plus
-- distractor/explanation fairness fixes. Validated against the combined
-- 300-question bank (positions, length gaps, phrase frequency, throwaways).

INSERT INTO public.challenges (slug,title,type,specialty,xp_reward,description,tags) VALUES
  ('j1939-quiet-at-55','The Truck That Went Quiet at 55','wiring','Diesel',160,'2016 Freightliner Cascadia, DD15. The instrument cluster blanks intermittently and six modules log ''abnormal update rate'' faults — mostly loaded, mostly at highway speed. Two shops deep with no fix; the fleet is losing patience.',ARRAY['J1939','Class 8','Fleet','Intermittent']),
  ('third-clutch-this-year','Third Clutch This Year','component','Automotive',150,'2017 Ram 2500 Cummins, G56 six-speed manual. Third clutch in fourteen months — the takeoff judder came back within weeks every time. Two installers, two brands, same result. The owner is convinced the parts are junk.',ARRAY['Clutch','Dual-Mass Flywheel','Manual','Repeat Failure']),
  ('morning-grouch-longcrank','The Morning Grouch','component','Diesel',150,'2015 Chevy Silverado 3500HD 6.6 Duramax (LML), 168k miles. Fifteen to twenty seconds of strong cranking on the first start of the day, then instant starts until tomorrow — even after a two-hour lunch stop. No codes, no smoke. Batteries and glow plugs already replaced elsewhere.',ARRAY['Duramax','Hard Start','Air In Fuel','Shop Lore'])
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.challenge_domains (challenge_id,domain) SELECT id,'Network'::public.skill_domain FROM public.challenges WHERE slug='j1939-quiet-at-55' ON CONFLICT DO NOTHING;
INSERT INTO public.challenge_domains (challenge_id,domain) SELECT id,'Drivetrain'::public.skill_domain FROM public.challenges WHERE slug='third-clutch-this-year' ON CONFLICT DO NOTHING;
INSERT INTO public.challenge_domains (challenge_id,domain) SELECT id,'Fuel'::public.skill_domain FROM public.challenges WHERE slug='morning-grouch-longcrank' ON CONFLICT DO NOTHING;

-- j1939-quiet-at-55
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'The modules on this truck talk over J1939. Structurally, what is J1939 closest to?','["LIN \u2014 a single master polling slave nodes over one wire", "High-speed CAN with a standardized message set \u2014 two wires, twin terminators", "Automotive Ethernet \u2014 switched point-to-point links between individual modules", "K-line \u2014 a slow shared diagnostic wire that a tester polls, module by module"]'::jsonb,1,'J1939 rides on CAN: a twisted pair, a terminated backbone, short stubs. What''s standardized on top is the message set — every make speaks the same parameter numbers — which is why one truck scan tool covers many brands.' FROM public.challenges WHERE slug='j1939-quiet-at-55' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',1,'The stored faults read ''abnormal update rate'' (FMI 9) rather than ''voltage high'' or ''circuit open''. What does that FMI family tell you before any meter comes out?','["The affected sensors are drifting out of calibration together as they age", "Modules are browning out from a shared supply voltage dip", "The cluster is displaying stale values held over in its message cache", "Messages are arriving late or missing \u2014 data delivery, not sensor values"]'::jsonb,3,'FMI 9 means a module didn''t receive an expected broadcast on schedule. Six modules complaining about update rate is the network path failing, not six sensors failing at once.' FROM public.challenges WHERE slug='j1939-quiet-at-55' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',2,'Backbone resistance at the 9-pin reads 60 ohms — parked, cold, engine off. The complaint happens loaded, at highway speed. What''s the standing of that reading?','["It clears the backbone entirely; the fault must live inside a module", "It''s invalid \u2014 bus resistance has to be measured with the network awake and talking", "It clears the backbone only as parked and cold \u2014 not under vibration and heat", "60 ohms is wrong for J1939; a healthy backbone should read 120"]'::jsonb,2,'60 ohms is exactly right — two 120-ohm terminators in parallel — but a static pass only speaks for static conditions. The complaint lives at speed, under load, with the cab working; the measurement hasn''t visited there yet.' FROM public.challenges WHERE slug='j1939-quiet-at-55' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'What instrumentation actually catches a bus fault that only appears on a loaded highway pull?','["A scope or CAN logger wired to the backbone, riding along while the truck works", "A resistance sweep at every connector immediately after the truck parks", "A second full-system scan the moment the driver phones in the event", "Swapping the cluster for a known-good spare from another truck in the same fleet"]'::jsonb,0,'The fault must be watched while it happens, so the instrument rides along. The fleet-favorite cluster swap can''t work here — the codes show half a dozen modules starving, and the cluster is just the victim the driver can see.' FROM public.challenges WHERE slug='j1939-quiet-at-55' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'The ride-along capture shows error bursts clustering whenever the cab rocks on its mounts. Where does that point on a cab-on-frame truck?','["The diagnostic connector''s stub, which flexes together with the dash harness", "A module ground screw inside the cab working loose at its boss", "The terminating resistor at the engine end overheating under load", "Backbone wiring crossing the cab-to-frame boundary, working at the flex point"]'::jsonb,3,'Errors that track cab motion indict whatever the cab''s motion exercises — and the backbone segments crossing from cab to frame are the wiring that flexes every time the cab rocks.' FROM public.challenges WHERE slug='j1939-quiet-at-55' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',5,'At the cab-to-frame bulkhead connector, the backbone pair''s terminals are green with crust and one crimp pulls out by hand. Two shops missed it. What would have found this the first time?','["A full harness replacement quote \u2014 comprehensive beats surgical on stubborn intermittents", "A load-and-wiggle test at the boundary connectors while watching the bus, done early", "An infrared scan of the bulkhead area right after a long highway run", "Replacing both terminating resistors up front as cheap insurance"]'::jsonb,1,'Intermittents get found by provoking the likeliest suspect while watching the signal. On any cab-on-frame truck the boundary connectors are the first flex suspects — a five-minute wiggle with a scope attached beats two shop visits.' FROM public.challenges WHERE slug='j1939-quiet-at-55' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'What''s the repair standard for corroded terminals in a sealed bulkhead connector that carries the backbone?','["Re-pin with the correct terminals and cavity seals \u2014 no solder bridges, no bypass loops", "Solder jumpers across the failed cavities and wrap them in self-fusing tape", "Pack every single cavity with contact grease and re-mate it until the reading finally cleans up", "Cut the connector out entirely and hard-splice the backbone straight through"]'::jsonb,0,'Sealed connectors are repaired by re-pinning with proper terminals and seals. Splicing the connector out of existence removes a service point, usually ruins the pair''s twist, and moves the corrosion problem to a homemade joint.' FROM public.challenges WHERE slug='j1939-quiet-at-55' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'Post-repair: how do you prove a fix for a fault that needed a loaded highway pull to appear?','["Clear the codes and re-check backbone resistance one final time", "Idle it in the yard for an hour with the scan tool attached", "Repeat the failing condition \u2014 logger on, loaded pull \u2014 and file the clean capture", "Release it back to the fleet and have the driver call in if the cluster blanks again"]'::jsonb,2,'The standard of proof is the failing condition reproduced clean. A capture file showing a quiet bus through the exact pull that used to kill the cluster is evidence a fleet manager can file.' FROM public.challenges WHERE slug='j1939-quiet-at-55' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'The fleet manager asks why the codes named six different modules when the fix was one connector. What''s the accurate explanation of how these faults attribute?','["All six modules really were damaged by the corrosion and recovered after the repair", "Every module logs its own starvation \u2014 comm faults name victims; the bus has no code", "The cluster relays fault codes on behalf of other modules, inflating the count", "The ECM mirrors its faults into the other modules'' memories for redundancy"]'::jsonb,1,'There is no code for ''the backbone connector is corroded'' — only each module reporting that data it expected never arrived. Communication faults are a list of witnesses, never a list of culprits.' FROM public.challenges WHERE slug='j1939-quiet-at-55' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'Generalize for the next intermittent-network truck: what''s the efficient sequence?','["Static resistance, then new terminators, then modules in order of code count", "Scan, clear, road test, and repeat until the pattern names one module", "Start from the newest repair in the truck''s history and work backward", "Quick static checks, then instrumented reproduction, then the flex points"]'::jsonb,3,'Cheap static tests earn their two minutes, but the verdict comes from watching the bus fail in its real conditions — and the suspect list starts where the harness moves: boundaries, hinges, mounts.' FROM public.challenges WHERE slug='j1939-quiet-at-55' ON CONFLICT DO NOTHING;

-- third-clutch-this-year
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'Two clutch brands, two different installers, three clutches, the same judder back within weeks. What does that pattern retire as a leading hypothesis?','["Driver technique, since the same owner drove through all three", "Installation error, since two different shops were involved", "Defective parts \u2014 different brands failing identically points away from the parts", "Rear main seal oil contamination, effectively ruled out here by the change of brands"]'::jsonb,2,'The parts hypothesis is dead: different brands failed identically. Two shops weakens installer error but doesn''t retire it — shared industry habits, like reusing a passable-looking flywheel, survive a change of shops. The constants move to the top of the list.' FROM public.challenges WHERE slug='third-clutch-this-year' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',1,'Name the components that stayed constant through all three clutch jobs on this truck.','["The flywheel (almost certainly reused), the hydraulics, driveline, and usage", "Only the driver \u2014 everything mechanical was renewed each time", "The pressure plate and disc, which carry over between kits", "Nothing \u2014 a clutch job renews the entire friction interface by definition"]'::jsonb,0,'A kit renews disc, pressure plate, and release bearing. Unless the invoices say otherwise, the flywheel gets reused or skimmed, the hydraulics stay, and the trailer keeps weighing what it weighs — that''s the suspect pool.' FROM public.challenges WHERE slug='third-clutch-this-year' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',2,'Invoices confirm the dual-mass flywheel was reused all three times — ''inspected, looked fine''. Why can a DMF pass a visual and still eat clutches?','["It can''t \u2014 a careful visual inspection is the industry-accepted test for dual-mass units", "Wear lives in its internal damping \u2014 rotational free play must be measured against spec", "Heat checking on the friction face only shows under dye penetrant", "The ring gear hides the wear marks on the friction surface from view"]'::jsonb,1,'A dual-mass flywheel wears in its damping mechanism, not its face. Free play and rock are measured in degrees against a published spec; a unit can look perfect while its springs are gone, feeding the diesel''s torsionals straight into every new disc.' FROM public.challenges WHERE slug='third-clutch-this-year' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'The DMF measures triple the allowed free play. The owner asks about the cheaper solid-flywheel conversion ''everyone on the forums runs''. What''s the honest trade-off on a diesel like this?','["There''s no real downside \u2014 dual-mass was a cost-cutting design from the factory to begin with", "Solid flywheels are racing parts and not legal on a road-registered truck", "The conversion voids the transmission warranty, which settles the question", "Cheaper and durable, but the damping job moves into the disc and driveline \u2014 an NVH trade"]'::jsonb,3,'The DMF exists to absorb diesel torsional shock. Conversions genuinely work and last, but the harshness has to go somewhere — gear rattle at idle and more driveline buzz. It''s an informed-choice conversation, not a scam in either direction.' FROM public.challenges WHERE slug='third-clutch-this-year' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'Beyond the flywheel, what hydraulic check belongs in this diagnosis before clutch number four goes in?','["Release stroke and crisp return \u2014 a lazy master or kinked line drags the disc", "Fluid color and level in the reservoir, which grade the whole hydraulic circuit", "Pedal free-height compared against the driver''s seating position", "A complete bleed and flush, which rules the hydraulics in or out on its own"]'::jsonb,0,'A release system that doesn''t stroke fully or return crisply keeps the disc partially loaded all day — heat, glaze, judder. Measure travel at the slave and watch the return; fresh fluid alone measures nothing.' FROM public.challenges WHERE slug='third-clutch-this-year' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',5,'Disc number three comes out glazed and heat-blued, with hot spots on the pressure plate. What story does that evidence tell?','["Defective friction material \u2014 heat-blueing of this kind is a known manufacturing signature", "Normal towing wear, just compressed into fewer miles than usual", "Slip and heat \u2014 the disc lived partially engaged, from drag, judder, or launch technique", "Oil mist contamination burning off the friction surface repeatedly"]'::jsonb,2,'Glaze, blueing, and hot spots are the metallurgy of slip. The disc is telling you it spent its short life partially engaged — the flywheel and hydraulic findings say what kept it there.' FROM public.challenges WHERE slug='third-clutch-this-year' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'New DMF measured in spec, new kit, hydraulics verified. What''s the delivery conversation, given the 15,500-lb fifth-wheel this truck tows — right at a manual 2500''s rating?','["None needed \u2014 the truck is factory-rated for that trailer, end of story", "Recommend trading for an automatic, which manages the heat better", "Suggest towing lighter until the new clutch beds in fully, after which there are no limits", "Launch technique under load \u2014 low gear, minimal slip \u2014 decides how long clutch four lives"]'::jsonb,3,'The hardware was guilty this time, but a trailer sitting right at the rating leaves no technique margin — low-gear, minimal-slip launches decide whether clutch four ages or dies. Covering both honestly keeps the next failure from becoming another parts argument.' FROM public.challenges WHERE slug='third-clutch-this-year' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'The owner asks why neither shop caught the flywheel. What''s the fair, professional answer?','["Both shops cut corners to win the job on price \u2014 it happens", "A passable-looking flywheel gets reused everywhere; the spec check is quick but isn''t habit", "Dual-mass wear genuinely can''t be detected without full disassembly", "Each judder event damaged the flywheel a little more deeply, hiding the original cause"]'::jsonb,1,'The charitable answer is also the true one: the measurement exists, it''s quick, and it gets skipped wherever ''looked fine'' is the culture. Same lesson as every pattern-versus-measurement case, applied to iron.' FROM public.challenges WHERE slug='third-clutch-this-year' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'What single line on this RO does the most to keep clutch number four from becoming clutch number five?','["''Installed premium-brand kit'' with all part numbers attached", "''Customer advised on towing habits'', logged as a liability protection note for the file", "The DMF free-play readings \u2014 the worn unit''s numbers beside the new unit''s spec", "''No warranty on friction materials'' printed in bold across the bottom line"]'::jsonb,2,'Numbers make a diagnosis inheritable. The next tech — or the next dispute — reads measured degrees of free play against spec and sees exactly why three clutches died, without needing anyone''s memory.' FROM public.challenges WHERE slug='third-clutch-this-year' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'Generalize the repeat-failure method: when the same part keeps dying, where does the diagnosis live?','["In what every failure shared \u2014 the constants around the part, not the part itself", "In the part''s brand and batch records, worked through the supplier", "In the newest failure only, since the physical evidence degrades with every event", "In one more replacement with an OEM part before any wider diagnosis"]'::jsonb,0,'A serially-failing part is usually the fuse, not the fault. Three dead clutches are three votes against everything they had in common — the flywheel bolted behind all of them most of all.' FROM public.challenges WHERE slug='third-clutch-this-year' ON CONFLICT DO NOTHING;

-- morning-grouch-longcrank
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',0,'Long crank on the first start of the day, instant restarts the rest of the day — even after a two-hour lunch. No codes. What variable does ''overnight only'' actually encode?','["Temperature \u2014 something contracts overnight in the cold and lets fuel seep past", "Battery chemistry \u2014 surface charge bleeding off overnight", "Oil drain-back thickening the very first crank of the day", "Time parked \u2014 something drains or admits air over hours; two hours isn''t enough"]'::jsonb,3,'The lunch restart makes time-parked the front-runner, not yet proof — after two hours the engine is still warm, so temperature isn''t cleanly separated until the designed soak test later in this case. What overnight uniquely has is hours for air to migrate in or fuel to drain back.' FROM public.challenges WHERE slug='morning-grouch-longcrank' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Easy',1,'Why does a common-rail diesel crank LONG when the low-pressure system has lost prime, rather than simply starting rough?','["The glow plugs won''t energize until fuel pressure is confirmed", "The ECM injects nothing until rail pressure hits threshold; the crank is re-priming time", "Air mixed into the fuel advances the injection timing beyond the cold-start map''s limits", "The lift pump waits for oil pressure before it starts to run"]'::jsonb,1,'Below minimum rail pressure the ECM injects nothing at all. Those fifteen seconds of healthy crank are the fuel system pushing air through and rebuilding pressure until injection is finally allowed.' FROM public.challenges WHERE slug='morning-grouch-longcrank' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',2,'What observation turns ''losing prime overnight'' from a story into evidence — without swapping any parts?','["A clear line or gauge left overnight \u2014 visible air or bled-down pressure by morning", "Cranking RPM compared cold versus warm on the scan tool", "A fuel sample drawn from the rail right after the long crank", "A fresh fuel filter installed on spec, watching whether the mornings improve after"]'::jsonb,0,'A transparent sight line captures the overnight event itself — bubbles you can photograph. The filter swap is a fair cheap test, but it answers once per morning; the clear line answers with evidence the first day.' FROM public.challenges WHERE slug='morning-grouch-longcrank' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',3,'Morning check: air bubbles sit in the clear line at the filter head outlet before the first start. Which part of the system does that indict?','["The high-pressure pump''s inlet seal, drawing in air under cranking vacuum", "The injector return circuit, back-feeding air toward the rail slowly through the night", "The suction side upstream \u2014 seals, primer, pickup, or fittings living under vacuum", "The tank vent, letting air into the tank as the fuel cools and contracts"]'::jsonb,2,'Air at the housing outlet got in somewhere upstream, where the system runs under vacuum and pulls inward at any imperfect seal. Pressurized sections leak fuel out, not air in — and the tank vent admitting air is its normal job.' FROM public.challenges WHERE slug='morning-grouch-longcrank' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',4,'On this truck the filter head sits on the suction side. What makes its service points — the spin-on filter seal and the bleeder screw O-ring — the first look for air?','["The filter head runs pressurized in operation, so its seals fail loudest", "They''re opened at every service \u2014 nicked, aged, or cross-seated more than sealed joints", "The head''s aluminum threads gall with age and let the filter seat crooked", "The head sits highest in the fuel system, so overnight air naturally collects up there"]'::jsonb,1,'The most-disturbed seals carry the highest base rate, and on this platform the whole head lives under suction — an imperfect seal pulls air inward instead of leaving a drip. That''s exactly why the leak never showed a wet spot for anyone to find.' FROM public.challenges WHERE slug='morning-grouch-longcrank' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Medium',5,'The bleeder screw''s O-ring shows a flattened, pinched section. What''s the repair plus same-visit verification?','["A new O-ring now, then a full week of owner-reported morning starts as the real test", "A complete new filter head assembly, since seals and castings age together", "Reseal the bleeder screw threads with thread sealant as added insurance", "New O-ring seated right, then a primer/vacuum-hold test to prove the seal today"]'::jsonb,3,'A vacuum-hold or hand-primer pressure test proves the repair before the truck leaves — same-day evidence. A week of mornings only re-tests, slowly, what the gauge can prove in ten minutes.' FROM public.challenges WHERE slug='morning-grouch-longcrank' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',6,'The vacuum test holds. What does the earlier ''batteries and glow plugs'' spend teach about long-crank triage?','["Nothing \u2014 both were reasonable age-based maintenance regardless", "That electrical always gets checked before fuel on any no-start", "Long crank got treated as weak crank \u2014 nobody split ''slow'' from ''strong but won''t light''", "The glow plugs were a correct call for cold-weather starts, just not the whole story"]'::jsonb,2,'The first split on any hard start is the character of the crank: slow and laboring points electrical; strong and fruitless points fuel or ignition enable. Fifteen seconds of healthy cranking was never a battery symptom.' FROM public.challenges WHERE slug='morning-grouch-longcrank' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',7,'The owner asks whether months of long cranking damaged anything. What''s the evidence-based answer here?','["Starter and battery duty, mostly \u2014 confirm crank time is normal again and close it", "The high-pressure pump ran dry each morning and deserves a preventive replacement now", "Cylinder washdown from unburned fuel will show up in the next oil sample", "The rail''s pressure relief valve took wear from the daily pressure spikes"]'::jsonb,0,'Below the injection threshold no fuel entered the cylinders, so washdown was never in play — the same fact that explained the long crank clears the engine. The wear went into the cranking system, and normal start times close the case.' FROM public.challenges WHERE slug='morning-grouch-longcrank' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',8,'Write the one-line condition statement for this RO that a warranty auditor could act on.','["''15-20s crank after 8+ hrs parked, instant same-day restarts \u2014 air at filter head, photo attached''", "''Hard start when cold, repaired'' plus the parts line", "''Customer states long crank; could not verify at the shop''", "''Intermittent extended crank observed \u2014 monitor the condition and return if it ever repeats''"]'::jsonb,0,'Condition, threshold, evidence: the complaint translated into a reproducible statement with proof attached. Everything else on the list is a story that dies with the visit.' FROM public.challenges WHERE slug='morning-grouch-longcrank' ON CONFLICT DO NOTHING;
INSERT INTO public.questions (challenge_id,difficulty,tier_order,question_text,options,correct_index,explanation)
SELECT id,'Hard',9,'Generalize: ''first start of the day'' complaints as a class. What''s the disciplined first split?','["Cold-soak testing on consecutive mornings in the shop''s coldest corner bay", "Time-parked versus temperature \u2014 a long warm soak or a short cold soak separates them", "Diesel and gas triage trees, which branch differently from the start", "Battery health checks first, since mornings are when batteries struggle hardest"]'::jsonb,1,'The two hypotheses predict different outcomes: park it long somewhere warm, or briefly somewhere cold, and one experiment tells you which variable the fault actually tracks — same move that decoded the ice-cream stop and the 3 a.m. minivan.' FROM public.challenges WHERE slug='morning-grouch-longcrank' ON CONFLICT DO NOTHING;

